import { Company } from '@/types';

export const companies: Company[] = [
  {
    id: 'comp-1',
    name: 'Fund "RC-Investment" ',
    type: 'Управляющая компания',
    country: 'Россия',
    description: 'Инвестиционный фонд, специализирующийся на проектах в странах Юго-Восточной Азии',
    contact: {
      email: 'info@rc-investment.com',
      phone: '+7 495 123-45-67',
      address: 'Москва, Россия',
    },
    projects: ['proj-1', 'proj-2', 'proj-3', 'proj-6', 'proj-7', 'proj-10'],
  },
  {
    id: 'comp-2',
    name: 'Ruma Organic Company',
    type: 'Дочерняя компания',
    country: 'Мьянма',
    description: 'Производитель органической сельскохозяйственной продукции',
    contact: {
      email: 'contact@ruma-organic.mm',
      phone: '+95 1 234 5678',
      address: 'Yangon, Myanmar',
    },
    projects: ['proj-1', 'proj-6', 'proj-7'],
  },
  {
    id: 'comp-3',
    name: 'Myanmar AnBang Investment Group Co., Ltd',
    type: 'Партнер',
    country: 'Мьянма',
    description: 'Местная компания по развитию сельского хозяйства',
    contact: {
      email: 'info@athagri.mm',
      phone: '+95 1 345 6789',
      address: 'Mandalay, Myanmar',
    },
    projects: ['proj-6', 'proj-7'],
  },
  {
    id: 'comp-4',
    name: 'RC-United Mining Company (RCM)',
    type: 'Дочерняя компания',
    country: 'Мьянма',
    description: 'Совместная горнодобывающая компания (51% RC, 49% местный партнер МЭК)',
    contact: {
      email: 'rcm@mining.mm',
      phone: '+95 2 456 7890',
      address: 'Mandalay Region, Myanmar',
    },
    projects: ['proj-2', 'proj-3'],
  },
  {
    id: 'comp-5',
    name: 'Everest Unites mining company ltd',
    type: 'Дочерняя компания',
    country: 'Мьянма',
    description: 'Совместная горнодобывающая компания с МЭК',
    contact: {
      email: 'contact@msg.mm',
      phone: '+95 2 567 8901',
      address: 'Mandalay, Myanmar',
    },
    projects: ['proj-2'],
  },
  {
    id: 'comp-6',
    name: 'RC & Star mining company ltd',
    type: 'Дочерняя компания',
    country: 'Мьянма',
    description: 'Совместная горнодобывающая компания с МЭК',
    contact: {
      email: 'info@cnmc.com.cn',
      phone: '+86 10 1234 5678',
      address: 'Yangon, Myanmar',
    },
    projects: ['proj-2'],
  },
  {
    id: 'comp-7',
    name: 'Мьянманская экономическая корпорация (МЭК)',
    type: 'Госкомпания Мьянмы',
    country: 'Мьянма',
    description: 'Государственная компания',
    contact: {
      email: 'info@myanmar-metals.gov.mm',
      phone: '+95 1 678 9012',
      address: 'Naypyidaw, Myanmar',
    },
    projects: ['proj-3'],
  },
  {
    id: 'comp-8',
    name: 'Ministry of Investment and Foreign Economic Relations (MIC)',
    type: 'Министерство/Ведомство',
    country: 'Мьянма',
    description: 'Министерство по инвестициям и внешнеэкономическим связям',
    contact: {
      email: 'mic@gov.mm',
      phone: '+95 67 123 456',
      address: 'Naypyidaw, Myanmar',
    },
    projects: [],
  },
  {
    id: 'comp-9',
    name: 'RC PLATFORM GROUP COMPANY LIMITED',
    type: 'Дочерняя компания',
    country: 'Мьянма',
    description: 'Управление по инвестициям и администрированию компаний',
    contact: {
      email: 'dica@gov.mm',
      phone: '+95 67 234 567',
      address: 'Naypyidaw, Myanmar',
    },
    projects: [],
  },
  {
    id: 'comp-10',
    name: 'Ministry of Agriculture',
    type: 'Министерство/Ведомство',
    country: 'Мьянма',
    description: 'Министерство сельского хозяйства',
    contact: {
      email: 'agriculture@gov.mm',
      phone: '+95 67 345 678',
      address: 'Naypyidaw, Myanmar',
    },
    projects: ['proj-6', 'proj-7'],
  },
  {
    id: 'comp-11',
    name: 'Ministry of Cooperation',
    type: 'Министерство/Ведомство',
    country: 'Мьянма',
    description: 'Министерство кооперации',
    contact: {
      email: 'cooperation@gov.mm',
      phone: '+95 67 456 789',
      address: 'Naypyidaw, Myanmar',
    },
    projects: [],
  },
  {
    id: 'comp-12',
    name: 'Ministry of Cooperation',
    type: 'Министерство/Ведомство',
    country: 'Мьянма',
    description: 'Министерство торговли',
    contact: {
      email: 'info@yangonport.gov.mm',
      phone: '+95 1 789 0123',
      address: 'Naypyidaw, Myanmar',
    },
    projects: ['proj-5'],
  },
  {
    id: 'comp-13',
    name: 'Ministry of Transport and Communications',
    type: 'Министерство/Ведомство',
    country: 'Мьянма',
    description: 'Министерство транспорта',
    contact: {
      email: 'info@thilawa.com.mm',
      phone: '+95 1 890 1234',
      address: 'Naypyidaw, Myanmar',
    },
    projects: ['proj-4'],
  },
  {
    id: 'comp-14',
    name: 'PYI HEIN TAUNGNYO CO., LTD',
    type: 'Партнер',
    country: 'Мьянма',
    description: 'Компания по поставкам нефтепродуктов',
    contact: {
      email: 'cce@construction.cn',
      phone: '+86 10 2345 6789',
      address: 'Yangon, Myanmar',
    },
    projects: ['proj-4', 'proj-8', 'proj-9'],
  },
  {
    id: 'comp-15',
    name: 'Ministry for Energy',
    type: 'Министерство/Ведомство',
    country: 'Мьянма',
    description: 'Местная строительная компания',
    contact: {
      email: 'info@myanmar-construction.mm',
      phone: '+95 1 901 2345',
      address: 'Naypyidaw, Myanmar',
    },
    projects: ['proj-1', 'proj-5', 'proj-6', 'proj-9'],
  },
];
