import { Document } from '@/types';

export const documents: Document[] = [
  // Меморандумы
  {
    id: 'doc-1',
    name: 'Меморандум о взаимопонимании - Министерство инвестиций',
    type: 'Меморандум',
    projectId: 'proj-1',
    uploadDate: '2026-03-01',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['меморандум', 'министерство инвестиций', 'сотрудничество'],
    fileSize: 2456789,
    fileType: 'application/pdf',
    url: '/documents/doc-1.pdf',
  },
  {
    id: 'doc-2',
    name: 'Меморандум о сотрудничестве - Министерство энергетики',
    type: 'Меморандум',
    projectId: 'proj-2',
    uploadDate: '2026-02-15',
    uploadedBy: 'user-2',
    version: 2,
    accessLevel: 'Confidential',
    tags: ['меморандум', 'энергетика', 'сотрудничество'],
    fileSize: 1890123,
    fileType: 'application/pdf',
    url: '/documents/doc-2.pdf',
  },
  // Конституция и правовая база
  {
    id: 'doc-3',
    name: 'Конституция Республики Союз Мьянма (2008)',
    type: 'Правовая база',
    projectId: undefined,
    uploadDate: '2026-01-10',
    uploadedBy: 'user-1',
    version: 1,
    accessLevel: 'Public',
    tags: ['конституция', 'правовая база', 'законодательство'],
    fileSize: 5678901,
    fileType: 'application/pdf',
    url: '/documents/doc-3.pdf',
  },
  {
    id: 'doc-4',
    name: 'Закон об иностранных инвестициях Мьянмы',
    type: 'Правовая база',
    projectId: undefined,
    uploadDate: '2026-01-15',
    uploadedBy: 'user-1',
    version: 1,
    accessLevel: 'Public',
    tags: ['инвестиции', 'закон', 'правовая база'],
    fileSize: 3456789,
    fileType: 'application/pdf',
    url: '/documents/doc-4.pdf',
  },
  {
    id: 'doc-5',
    name: 'Регламент MIC - Порядок получения разрешений',
    type: 'Правовая база',
    projectId: undefined,
    uploadDate: '2026-02-01',
    uploadedBy: 'user-2',
    version: 3,
    accessLevel: 'Confidential',
    tags: ['MIC', 'регламент', 'разрешения'],
    fileSize: 1234567,
    fileType: 'application/pdf',
    url: '/documents/doc-5.pdf',
  },
  // Лицензии
  {
    id: 'doc-6',
    name: 'Лицензия на добычу никеля - Tagaung Taung',
    type: 'Лицензия',
    projectId: 'proj-2',
    uploadDate: '2026-01-15',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['лицензия', 'добыча', 'никель'],
    fileSize: 345678,
    fileType: 'application/pdf',
    url: '/documents/doc-6.pdf',
  },
  {
    id: 'doc-7',
    name: 'Лицензия на экспорт минеральных ресурсов',
    type: 'Лицензия',
    projectId: 'proj-3',
    uploadDate: '2026-03-20',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['лицензия', 'экспорт', 'минералы'],
    fileSize: 456789,
    fileType: 'application/pdf',
    url: '/documents/doc-7.pdf',
  },
  {
    id: 'doc-8',
    name: 'Разрешение на строительство завода удобрений',
    type: 'Лицензия',
    projectId: 'proj-1',
    uploadDate: '2026-04-10',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['разрешение', 'строительство', 'завод'],
    fileSize: 567890,
    fileType: 'application/pdf',
    url: '/documents/doc-8.pdf',
  },
  // Соглашения
  {
    id: 'doc-9',
    name: 'Соглашение о разделе продукции - Bawdwin',
    type: 'Соглашение',
    projectId: 'proj-3',
    uploadDate: '2026-02-28',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['соглашение', 'продукция', 'Bawdwin'],
    fileSize: 2345678,
    fileType: 'application/pdf',
    url: '/documents/doc-9.pdf',
  },
  {
    id: 'doc-10',
    name: 'Соглашение о поставке оборудования',
    type: 'Соглашение',
    projectId: 'proj-1',
    uploadDate: '2026-05-15',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['соглашение', 'поставка', 'оборудование'],
    fileSize: 1567890,
    fileType: 'application/pdf',
    url: '/documents/doc-10.pdf',
  },
  // Договоры
  {
    id: 'doc-11',
    name: 'Договор на строительство Mobile Factory',
    type: 'Договор',
    projectId: 'proj-1',
    uploadDate: '2026-03-01',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['договор', 'строительство', 'подряд'],
    fileSize: 2456789,
    fileType: 'application/pdf',
    url: '/documents/doc-11.pdf',
  },
  {
    id: 'doc-12',
    name: 'Договор с подрядчиком на строительство дорог',
    type: 'Договор',
    projectId: 'proj-2',
    uploadDate: '2026-02-01',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['договор', 'подряд', 'инфраструктура'],
    fileSize: 1890123,
    fileType: 'application/pdf',
    url: '/documents/doc-12.pdf',
  },
  // Финансовые модели
  {
    id: 'doc-13',
    name: 'Финансовая модель Mobile Factory',
    type: 'Финансовая модель',
    projectId: 'proj-1',
    uploadDate: '2026-01-20',
    uploadedBy: 'user-1',
    version: 3,
    accessLevel: 'Strictly Confidential',
    tags: ['финансы', 'модель', 'бюджет'],
    fileSize: 3456789,
    fileType: 'application/vnd.ms-excel',
    url: '/documents/doc-13.xlsx',
  },
  // Отчеты
  {
    id: 'doc-14',
    name: 'Геологический отчет Tagaung Taung',
    type: 'Отчет',
    projectId: 'proj-2',
    uploadDate: '2026-09-30',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['геология', 'разведка', 'отчет'],
    fileSize: 8901234,
    fileType: 'application/pdf',
    url: '/documents/doc-14.pdf',
  },
  {
    id: 'doc-15',
    name: 'Экологическая экспертиза Bawdwin Mine',
    type: 'Отчет',
    projectId: 'proj-3',
    uploadDate: '2026-04-30',
    uploadedBy: 'user-7',
    version: 1,
    accessLevel: 'Public',
    tags: ['экология', 'экспертиза', 'окружающая среда'],
    fileSize: 5678901,
    fileType: 'application/pdf',
    url: '/documents/doc-15.pdf',
  },
  // Сертификаты
  {
    id: 'doc-16',
    name: 'Сертификат GOST 33980-2016 (Bioklad)',
    type: 'Сертификат',
    projectId: 'proj-1',
    uploadDate: '2026-03-15',
    uploadedBy: 'user-5',
    version: 1,
    accessLevel: 'Public',
    tags: ['сертификат', 'GOST', 'продукт'],
    fileSize: 256789,
    fileType: 'application/pdf',
    url: '/documents/doc-16.pdf',
  },
  // Переписка
  {
    id: 'doc-17',
    name: 'Переписка с Ministry of Agriculture',
    type: 'Переписка',
    projectId: 'proj-7',
    uploadDate: '2026-05-15',
    uploadedBy: 'user-5',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['переписка', 'министерство', 'согласование'],
    fileSize: 234567,
    fileType: 'application/pdf',
    url: '/documents/doc-17.pdf',
  },
  {
    id: 'doc-18',
    name: 'Письмо в МИД - Запрос поддержки проекта',
    type: 'Переписка',
    projectId: 'proj-2',
    uploadDate: '2026-06-01',
    uploadedBy: 'user-2',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['письмо', 'МИД', 'поддержка'],
    fileSize: 345678,
    fileType: 'application/pdf',
    url: '/documents/doc-18.pdf',
  },
  // Технические документы
  {
    id: 'doc-19',
    name: 'Технические спецификации производственной линии',
    type: 'Техническая документация',
    projectId: 'proj-1',
    uploadDate: '2026-06-15',
    uploadedBy: 'user-5',
    version: 2,
    accessLevel: 'Confidential',
    tags: ['техдокументация', 'спецификации', 'оборудование'],
    fileSize: 4567890,
    fileType: 'application/pdf',
    url: '/documents/doc-19.pdf',
  },
  {
    id: 'doc-20',
    name: 'Спецификации обогатительной линии',
    type: 'Техническая документация',
    projectId: 'proj-3',
    uploadDate: '2026-09-01',
    uploadedBy: 'user-7',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['техдокументация', 'оборудование', 'обогащение'],
    fileSize: 6789012,
    fileType: 'application/pdf',
    url: '/documents/doc-20.pdf',
  },
];