import { Document } from '@/types';

export const documents: Document[] = [
  {
    id: 'doc-1',
    name: 'Договор на строительство Mobile Factory',
    type: 'Договор',
    projectId: 'proj-1',
    uploadDate: '2026-03-01',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['строительство', 'подряд', 'договор'],
    fileSize: 2456789,
    fileType: 'application/pdf',
    url: '/documents/doc-1.pdf',
  },
  {
    id: 'doc-2',
    name: 'MIC Approval Letter',
    type: 'Разрешение',
    projectId: 'proj-1',
    uploadDate: '2026-03-05',
    uploadedBy: 'user-2',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['MIC', 'разрешение', 'одобрение'],
    fileSize: 156789,
    fileType: 'application/pdf',
    url: '/documents/doc-2.pdf',
  },
  {
    id: 'doc-3',
    name: 'Финансовая модель Mobile Factory',
    type: 'Финансовая модель',
    projectId: 'proj-1',
    uploadDate: '2026-01-20',
    uploadedBy: 'user-1',
    version: 3,
    accessLevel: 'Strictly Confidential',
    tags: ['финансы', 'модель', 'бюджет'],
    fileSize: 3456789,
    fileType: 'application/vnd.ms-excel',
    url: '/documents/doc-3.xlsx',
  },
  {
    id: 'doc-4',
    name: 'Импортное разрешение на оборудование',
    type: 'Разрешение',
    projectId: 'proj-1',
    uploadDate: '2026-04-10',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['импорт', 'таможня', 'оборудование'],
    fileSize: 456789,
    fileType: 'application/pdf',
    url: '/documents/doc-4.pdf',
  },
  {
    id: 'doc-5',
    name: 'Сертификат GOST 33980-2016 (Bioklad)',
    type: 'Сертификат',
    projectId: 'proj-1',
    uploadDate: '2026-03-15',
    uploadedBy: 'user-5',
    version: 1,
    accessLevel: 'Public',
    tags: ['сертификат', 'GOST', 'продукт'],
    fileSize: 256789,
    fileType: 'application/pdf',
    url: '/documents/doc-5.pdf',
  },
  {
    id: 'doc-6',
    name: 'Отчет о выполнении работ - Август 2024',
    type: 'Отчет',
    projectId: 'proj-1',
    uploadDate: '2026-09-05',
    uploadedBy: 'user-2',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['отчет', 'прогресс', 'август'],
    fileSize: 1234567,
    fileType: 'application/pdf',
    url: '/documents/doc-6.pdf',
  },
  {
    id: 'doc-7',
    name: 'Технические спецификации производственной линии',
    type: 'Техническая документация',
    projectId: 'proj-1',
    uploadDate: '2026-06-15',
    uploadedBy: 'user-5',
    version: 2,
    accessLevel: 'Confidential',
    tags: ['техдокументация', 'спецификации', 'оборудование'],
    fileSize: 4567890,
    fileType: 'application/pdf',
    url: '/documents/doc-7.pdf',
  },
  {
    id: 'doc-8',
    name: 'Лицензия на добычу никеля',
    type: 'Разрешение',
    projectId: 'proj-2',
    uploadDate: '2026-01-15',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['лицензия', 'добыча', 'никель'],
    fileSize: 345678,
    fileType: 'application/pdf',
    url: '/documents/doc-8.pdf',
  },
  {
    id: 'doc-9',
    name: 'Геологический отчет Tagaung Taung',
    type: 'Отчет',
    projectId: 'proj-2',
    uploadDate: '2026-09-30',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['геология', 'разведка', 'отчет'],
    fileSize: 8901234,
    fileType: 'application/pdf',
    url: '/documents/doc-9.pdf',
  },
  {
    id: 'doc-10',
    name: 'Договор с подрядчиком на строительство дорог',
    type: 'Договор',
    projectId: 'proj-2',
    uploadDate: '2026-02-01',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['договор', 'подряд', 'инфраструктура'],
    fileSize: 1890123,
    fileType: 'application/pdf',
    url: '/documents/doc-10.pdf',
  },
  {
    id: 'doc-11',
    name: 'Экологическая экспертиза Bawdwin Mine',
    type: 'Отчет',
    projectId: 'proj-3',
    uploadDate: '2026-04-30',
    uploadedBy: 'user-7',
    version: 1,
    accessLevel: 'Public',
    tags: ['экология', 'экспертиза', 'окружающая среда'],
    fileSize: 5678901,
    fileType: 'application/pdf',
    url: '/documents/doc-11.pdf',
  },
  {
    id: 'doc-12',
    name: 'Оценка запасов месторождения',
    type: 'Отчет',
    projectId: 'proj-3',
    uploadDate: '2026-04-30',
    uploadedBy: 'user-4',
    version: 1,
    accessLevel: 'Strictly Confidential',
    tags: ['запасы', 'оценка', 'месторождение'],
    fileSize: 3456789,
    fileType: 'application/pdf',
    url: '/documents/doc-12.pdf',
  },
  {
    id: 'doc-13',
    name: 'Спецификации обогатительной линии',
    type: 'Техническая документация',
    projectId: 'proj-3',
    uploadDate: '2026-09-01',
    uploadedBy: 'user-7',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['техдокументация', 'оборудование', 'обогащение'],
    fileSize: 6789012,
    fileType: 'application/pdf',
    url: '/documents/doc-13.pdf',
  },
  {
    id: 'doc-14',
    name: 'Переписка с Ministry of Agriculture',
    type: 'Переписка',
    projectId: 'proj-7',
    uploadDate: '2026-05-15',
    uploadedBy: 'user-5',
    version: 1,
    accessLevel: 'Confidential',
    tags: ['переписка', 'министерство', 'согласование'],
    fileSize: 234567,
    fileType: 'application/pdf',
    url: '/documents/doc-14.pdf',
  },
  {
    id: 'doc-15',
    name: 'Фото строительной площадки',
    type: 'Скан/фото',
    projectId: 'proj-1',
    uploadDate: '2026-08-20',
    uploadedBy: 'user-3',
    version: 1,
    accessLevel: 'Public',
    tags: ['фото', 'стройка', 'прогресс'],
    fileSize: 5678901,
    fileType: 'image/jpeg',
    url: '/documents/doc-15.jpg',
  },
];
