import { ActivityEvent, KPIData } from '@/types';

export const events: ActivityEvent[] = [
  {
    id: 'evt-1',
    type: 'task_completed',
    title: 'Задача завершена',
    description: 'Подготовка и подача материалов в MIC завершена',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
    taskId: 'task-1',
    userId: 'user-2',
  },
  {
    id: 'evt-2',
    type: 'risk_detected',
    title: 'Обнаружен риск',
    description: 'Задержка сертификации может повлиять на сроки запуска',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
    userId: 'user-5',
    riskLevel: 'Высокий',
  },
  {
    id: 'evt-3',
    type: 'document_added',
    title: 'Документ добавлен',
    description: 'Новый договор на строительство добавлен в проект Mobile Factory Ruma',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
    userId: 'user-3',
  },
  {
    id: 'evt-4',
    type: 'milestone_reached',
    title: 'Веха достигнута',
    description: 'Установка оборудования завершена в срок',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
    userId: 'user-5',
  },
  {
    id: 'evt-5',
    type: 'deadline_approaching',
    title: 'Приближается дедлайн',
    description: 'До завершения задачи "Запуск продаж" осталось 15 дней',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-1',
    taskId: 'task-9',
    userId: 'user-2',
  },
  {
    id: 'evt-6',
    type: 'task_completed',
    title: 'Задача завершена',
    description: 'Геологическая разведка месторождения завершена',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-2',
    taskId: 'task-11',
    userId: 'user-4',
  },
  {
    id: 'evt-7',
    type: 'risk_detected',
    title: 'Обнаружен риск',
    description: 'Возможные задержки в поставке горного оборудования',
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-2',
    userId: 'user-6',
    riskLevel: 'Средний',
  },
  {
    id: 'evt-8',
    type: 'milestone_reached',
    title: 'Веха достигнута',
    description: 'Получена лицензия на добычу никеля',
    timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-2',
    userId: 'user-4',
  },
  {
    id: 'evt-9',
    type: 'document_added',
    title: 'Документ добавлен',
    description: 'Экологическая экспертиза добавлена в проект Bawdwin Mine',
    timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-3',
    userId: 'user-7',
  },
  {
    id: 'evt-10',
    type: 'risk_detected',
    title: 'Критический риск',
    description: 'Необходимо усилить меры безопасности в шахте',
    timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    projectId: 'proj-3',
    userId: 'user-4',
    riskLevel: 'Высокий',
  },
];

export const kpiData: KPIData = {
  activeProjects: 12,
  tasksInProgress: 87,
  tasksOverdue: 14,
  highRisks: 5,
  documentsForApproval: 23,
  planCompletion: 78,
};
