import { MapPoint } from '@/types';

export const mapPoints: MapPoint[] = [
  {
    id: 'map-1',
    name: 'Завод удобрений в Нейпьидо',
    type: 'factory',
    coordinates: {
      lat: 16.8661,
      lng: 96.1951,
    },
    projectId: 'proj-1',
    status: 'Активен',
    description: 'Фабрика по производству органических удобрений и биопрепаратов',
  },
  {
    id: 'map-2',
    name: 'Геологоразведка и добыча РЗМ',
    type: 'mine',
    coordinates: {
      lat: 23.0866,
      lng: 96.0686,
    },
    projectId: 'proj-2',
    status: 'Активен',
    description: 'Разработка месторождения бериллия',
  },
  {
    id: 'map-3',
    name: 'Торговый дом',
    type: 'mine',
    coordinates: {
      lat: 23.2733,
      lng: 97.3256,
    },
    projectId: 'proj-3',
    status: 'Активен',
    description: 'Организация и строительство импортно-экспортного хаба',
  },
  {
    id: 'map-4',
    name: 'Рисовый проект',
    type: 'factory',
    coordinates: {
      lat: 16.7050,
      lng: 96.2338,
    },
    projectId: 'proj-4',
    status: 'Завершен',
    description: 'Фабрика в специальной экономической зоне Thilawa',
  },
  {
    id: 'map-5',
    name: 'Завод удобрений Иеравади',
    type: 'port',
    coordinates: {
      lat: 16.7700,
      lng: 96.1600,
    },
    projectId: 'proj-5',
    status: 'Активен',
    description: 'Логистический узел в порту Янгона',
  },
  {
    id: 'map-6',
    name: 'Центр единоборств',
    type: 'factory',
    coordinates: {
      lat: 21.9588,
      lng: 96.0891,
    },
    projectId: 'proj-6',
    status: 'Планирование',
    description: 'Завод по производству органических удобрений',
  },
  {
    id: 'map-7',
    name: 'Agricultural R&D Center',
    type: 'factory',
    coordinates: {
      lat: 16.8050,
      lng: 96.1560,
    },
    projectId: 'proj-7',
    status: 'Активен',
    description: 'Исследовательский центр по сельскохозяйственным технологиям',
  },
  {
    id: 'map-8',
    name: 'Monosilicic Acid Production',
    type: 'factory',
    coordinates: {
      lat: 16.8500,
      lng: 96.1800,
    },
    projectId: 'proj-8',
    status: 'Активен',
    description: 'Производство монокремниевой кислоты',
  },
  {
    id: 'map-9',
    name: 'Cement Plant Upgrade',
    type: 'factory',
    coordinates: {
      lat: 20.1489,
      lng: 92.8782,
    },
    projectId: 'proj-9',
    status: 'Активен',
    description: 'Модернизация цементного завода',
  },
  {
    id: 'map-10',
    name: 'Mobile Unit Deployment',
    type: 'factory',
    coordinates: {
      lat: 17.0350,
      lng: 96.4800,
    },
    projectId: 'proj-10',
    status: 'Планирование',
    description: 'Развертывание мобильных производственных комплексов',
  },
  {
    id: 'map-11',
    name: 'Mandalay Warehouse',
    type: 'warehouse',
    coordinates: {
      lat: 21.9750,
      lng: 96.0850,
    },
    status: 'Активен',
    description: 'Складской комплекс в Мандалае',
  },
  {
    id: 'map-12',
    name: 'Naypyidaw Logistics Hub',
    type: 'logistics',
    coordinates: {
      lat: 19.7633,
      lng: 96.0785,
    },
    status: 'Активен',
    description: 'Логистический центр в столице',
  },
  {
    id: 'map-13',
    name: 'Mawlamyine Port',
    type: 'port',
    coordinates: {
      lat: 16.4919,
      lng: 97.6278,
    },
    status: 'Активен',
    description: 'Морской порт Моламьяйн',
  },
  {
    id: 'map-14',
    name: 'Pathein Warehouse',
    type: 'warehouse',
    coordinates: {
      lat: 16.7791,
      lng: 94.7325,
    },
    status: 'Активен',
    description: 'Складской комплекс в Патейне',
  },
  {
    id: 'map-15',
    name: 'Myitkyina Distribution Center',
    type: 'logistics',
    coordinates: {
      lat: 25.3833,
      lng: 97.3964,
    },
    status: 'Активен',
    description: 'Распределительный центр на севере',
  },
];
