import { Ministry, MinistryCommunication, MinistryAgreement } from '@/types';

export const ministries: Ministry[] = [
  {
    id: 'min-1',
    name: 'Министерство инвестиций',
    fullName: 'Ministry of Investment and Foreign Economic Relations (MIC)',
    ministerName: 'U Zaw Min',
    type: 'Министерство инвестиций',
    description: 'Министерство по инвестициям и внешнеэкономическим связям. Отвечает за регулирование иностранных инвестиций, выдачу разрешений на деятельность и координацию экономических проектов.',
    cooperationLevel: 'Стратегический партнер',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 123 456',
      email: 'mic@gov.mm',
      website: 'https://mic.gov.mm',
      contactPerson: 'U Aung Min',
      contactPosition: 'Директор департамента инвестиций',
    },
    relatedProjects: ['proj-1', 'proj-2', 'proj-3'],
    communicationsCount: 24,
    agreementsCount: 3,
    pendingResponses: 2,
    lastCommunicationDate: '2024-03-15',
  },
  {
    id: 'min-2',
    name: 'Министерство иностранных дел',
    fullName: 'Ministry of Foreign Affairs',
    ministerName: 'Daw Thida Myint',
    type: 'Министерство иностранных дел',
    description: 'Министерство иностранных дел. Отвечает за дипломатические отношения, координацию международных проектов и визовую поддержку.',
    cooperationLevel: 'Ключевой партнер',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 234 567',
      email: 'mofa@gov.mm',
      website: 'https://mofa.gov.mm',
      contactPerson: 'Daw Hla Hla',
      contactPosition: 'Заместитель директора консульского отдела',
    },
    relatedProjects: ['proj-1', 'proj-4'],
    communicationsCount: 18,
    agreementsCount: 2,
    pendingResponses: 1,
    lastCommunicationDate: '2024-03-10',
  },
  {
    id: 'min-3',
    name: 'Министерство природных ресурсов',
    fullName: 'Ministry of Natural Resources and Environmental Conservation',
    ministerName: 'U Aung Kyaw',
    type: 'Министерство природных ресурсов',
    description: 'Министерство природных ресурсов и охраны окружающей среды. Регулирует землепользование, экологические разрешения и охрану природных ресурсов.',
    cooperationLevel: 'Ключевой партнер',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 345 678',
      email: 'monrec@gov.mm',
      website: 'https://monrec.gov.mm',
      contactPerson: 'U Kyaw Win',
      contactPosition: 'Начальник управления экологической экспертизы',
    },
    relatedProjects: ['proj-2', 'proj-3'],
    communicationsCount: 32,
    agreementsCount: 4,
    pendingResponses: 3,
    lastCommunicationDate: '2024-03-18',
  },
  {
    id: 'min-4',
    name: 'Министерство энергетики',
    fullName: 'Ministry of Energy',
    ministerName: 'U Than Aung',
    type: 'Министерство энергетики',
    description: 'Министерство энергетики. Отвечает за регулирование энергетического сектора, лицензирование и координацию энергетических проектов.',
    cooperationLevel: 'Активное взаимодействие',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 456 789',
      email: 'moe@gov.mm',
      website: 'https://moe.gov.mm',
      contactPerson: 'U Thein Aung',
      contactPosition: 'Директор энергетического департамента',
    },
    relatedProjects: ['proj-5', 'proj-9'],
    communicationsCount: 15,
    agreementsCount: 2,
    pendingResponses: 1,
    lastCommunicationDate: '2024-03-12',
  },
  {
    id: 'min-5',
    name: 'Министерство торговли',
    fullName: 'Ministry of Commerce',
    ministerName: 'Daw Mya Thida',
    type: 'Министерство торговли',
    description: 'Министерство торговли. Регулирует торговую деятельность, экспорт/импорт, лицензирование торговых операций.',
    cooperationLevel: 'Активное взаимодействие',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 567 890',
      email: 'moc@gov.mm',
      website: 'https://moc.gov.mm',
      contactPerson: 'Daw Aye Aye',
      contactPosition: 'Директор отдела внешней торговли',
    },
    relatedProjects: ['proj-6', 'proj-7'],
    communicationsCount: 20,
    agreementsCount: 3,
    pendingResponses: 2,
    lastCommunicationDate: '2024-03-14',
  },
  {
    id: 'min-6',
    name: 'Министерство сельского хозяйства',
    fullName: 'Ministry of Agriculture, Livestock and Irrigation',
    ministerName: 'U Myo Min',
    type: 'Министерство сельского хозяйства',
    description: 'Министерство сельского хозяйства, животноводства и ирригации. Отвечает за развитие аграрного сектора и регулирование сельскохозяйственной деятельности.',
    cooperationLevel: 'Активное взаимодействие',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 678 901',
      email: 'moali@gov.mm',
      website: 'https://moali.gov.mm',
      contactPerson: 'U Win Pe',
      contactPosition: 'Заместитель министра',
    },
    relatedProjects: ['proj-6', 'proj-7'],
    communicationsCount: 28,
    agreementsCount: 5,
    pendingResponses: 1,
    lastCommunicationDate: '2024-03-16',
  },
  {
    id: 'min-7',
    name: 'Министерство финансов',
    fullName: 'Ministry of Finance and Revenue',
    ministerName: 'U Win Shein',
    type: 'Министерство финансов',
    description: 'Министерство финансов и налогов. Отвечает за налоговое регулирование, бюджетное планирование и финансовый контроль.',
    cooperationLevel: 'Базовое взаимодействие',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 789 012',
      email: 'mof@gov.mm',
      website: 'https://mof.gov.mm',
      contactPerson: 'U Myint Aung',
      contactPosition: 'Начальник налогового управления',
    },
    relatedProjects: [],
    communicationsCount: 8,
    agreementsCount: 1,
    pendingResponses: 0,
    lastCommunicationDate: '2024-02-28',
  },
  {
    id: 'min-8',
    name: 'Министерство транспорта',
    fullName: 'Ministry of Transport and Communications',
    ministerName: 'U Thant Sin Maung',
    type: 'Министерство транспорта',
    description: 'Министерство транспорта и коммуникаций. Регулирует транспортную инфраструктуру, логистику и телекоммуникации.',
    cooperationLevel: 'Базовое взаимодействие',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 890 123',
      email: 'motc@gov.mm',
      website: 'https://motc.gov.mm',
      contactPerson: 'U Tun Kyi',
      contactPosition: 'Директор транспортного департамента',
    },
    relatedProjects: ['proj-4', 'proj-8'],
    communicationsCount: 12,
    agreementsCount: 2,
    pendingResponses: 1,
    lastCommunicationDate: '2024-03-08',
  },
  {
    id: 'min-9',
    name: 'Министерство промышленности',
    fullName: 'Ministry of Industry',
    ministerName: 'Не назначен',
    type: 'Министерство промышленности',
    description: 'Министерство промышленности. Отвечает за развитие промышленного сектора, регулирование производственной деятельности и промышленных зон.',
    cooperationLevel: 'Нет взаимодействия',
    contact: {
      address: 'Naypyidaw, Myanmar',
      phone: '+95 67 901 234',
      email: 'moi@gov.mm',
      website: 'https://moi.gov.mm',
      contactPerson: 'Не назначен',
      contactPosition: '',
    },
    relatedProjects: [],
    communicationsCount: 2,
    agreementsCount: 0,
    pendingResponses: 0,
    lastCommunicationDate: '2024-01-15',
  },
];

export const ministryCommunications: MinistryCommunication[] = [
  {
    id: 'comm-1',
    subject: 'Запрос на продление лицензии на добычу полезныхных ископаемых',
    description: 'Запрос в Министерство инвестиций на продление лицензии на добычу полезныхных ископаемых для проекта RC-United Mining Company на дополнительный срок 3 года.',
    ministryId: 'min-1',
    category: 'Письмо',
    status: 'Ожидает ответа',
    date: '2024-03-10',
    deadline: '2024-04-10',
    projectId: 'proj-2',
    attachments: ['license_extension_request.pdf', 'supporting_documents.pdf'],
    author: 'Иванов И.И.',
    assignedTo: 'Петров П.П.',
    priority: 'Высокий',
    notes: 'Требуется подготовка дополнительных документов по запросу министерства',
  },
  {
    id: 'comm-2',
    subject: 'Меморандум о взаимопонимании по проекту Ruma Organic',
    description: 'Подготовка меморандума о взаимопонимании с Министерством сельского хозяйства по проекту органического земледелия Ruma Organic.',
    ministryId: 'min-6',
    category: 'Меморандум',
    status: 'На рассмотрении',
    date: '2024-03-05',
    projectId: 'proj-6',
    attachments: ['mou_ruma_organic.pdf'],
    author: 'Сидоров С.С.',
    assignedTo: 'Кузнецов К.К.',
    priority: 'Средний',
  },
  {
    id: 'comm-3',
    subject: 'Экологическая оценка для проекта добычи никеля',
    description: 'Запрос на проведение экологической экспертизы для проекта добычи никеля в рамках RC-United Mining Company.',
    ministryId: 'min-3',
    category: 'Письмо',
    status: 'Получено',
    date: '2024-03-15',
    responseDate: '2024-03-18',
    projectId: 'proj-3',
    attachments: ['env_assessment_request.pdf', 'project_details.pdf'],
    author: 'Иванов И.И.',
    assignedTo: 'Петров П.П.',
    priority: 'Высокий',
  },
  {
    id: 'comm-4',
    subject: 'Ответ на запрос по экологической оценке проекта никеля',
    description: 'Ответ Министерства природных ресурсов на запрос по проведению экологической экспертизы проекта добычи никеля.',
    ministryId: 'min-3',
    category: 'Ответ',
    status: 'Завершено',
    date: '2024-03-18',
    projectId: 'proj-3',
    attachments: ['env_assessment_response.pdf'],
    author: 'U Kyaw Win',
    assignedTo: 'Иванов И.И.',
    priority: 'Средний',
  },
  {
    id: 'comm-5',
    subject: 'Согласование тарифов на экспорт органической продукции',
    description: 'Запрос в Министерство торговли на согласование тарифных ставок для экспорта органической продукции.',
    ministryId: 'min-5',
    category: 'Письмо',
    status: 'Ожидает ответа',
    date: '2024-03-12',
    deadline: '2024-04-12',
    projectId: 'proj-7',
    attachments: ['export_tariff_request.pdf', 'product_catalog.pdf'],
    author: 'Сидоров С.С.',
    assignedTo: 'Кузнецов К.К.',
    priority: 'Средний',
  },
  {
    id: 'comm-6',
    subject: 'Протокол встречи по энергетическому проекту',
    description: 'Протокол рабочей встречи с Министерством энергетики по вопросам развития инфраструктурного проекта.',
    ministryId: 'min-4',
    category: 'Протокол',
    status: 'Завершено',
    date: '2024-02-20',
    projectId: 'proj-9',
    attachments: ['meeting_protocol.pdf'],
    author: 'Петров П.П.',
    priority: 'Низкий',
  },
  {
    id: 'comm-7',
    subject: 'Запрос на получение разрешения на строительство порта',
    description: 'Запрос в Министерство транспорта на получение разрешения на строительство грузового порта для логистического проекта.',
    ministryId: 'min-8',
    category: 'Письмо',
    status: 'Отправлено',
    date: '2024-03-08',
    deadline: '2024-04-08',
    projectId: 'proj-8',
    attachments: ['port_construction_request.pdf', 'preliminary_design.pdf'],
    author: 'Кузнецов К.К.',
    assignedTo: 'Петров П.П.',
    priority: 'Высокий',
  },
  {
    id: 'comm-8',
    subject: 'Запрос на получение разрешения на добычу',
    description: 'Официальный запрос на получение разрешения на добычу полезных ископаемых для проекта RC-United Mining Company.',
    ministryId: 'min-1',
    category: 'Письмо',
    status: 'Отправлено',
    date: '2024-03-15',
    deadline: '2024-04-15',
    projectId: 'proj-2',
    attachments: ['mining_permit_request.pdf', 'geological_survey.pdf'],
    author: 'Иванов И.И.',
    assignedTo: 'Петров П.П.',
    priority: 'Критический',
  },
  {
    id: 'comm-9',
    subject: 'Дипломатическая нота по визовым вопросам',
    description: 'Дипломатическая нота в Министерство иностранных дел по вопросам упрощения визового режима для сотрудников компании.',
    ministryId: 'min-2',
    category: 'Письмо',
    status: 'На рассмотрении',
    date: '2024-03-10',
    attachments: ['diplomatic_note.pdf'],
    author: 'Сидоров С.С.',
    assignedTo: 'Иванов И.И.',
    priority: 'Средний',
  },
  {
    id: 'comm-10',
    subject: 'Ответ по визовым вопросам',
    description: 'Ответ Министерства иностранных дел на запрос по упрощению визового режима для сотрудников.',
    ministryId: 'min-2',
    category: 'Ответ',
    status: 'Завершено',
    date: '2024-03-14',
    attachments: ['visa_response.pdf'],
    author: 'Daw Hla Hla',
    assignedTo: 'Сидоров С.С.',
    priority: 'Средний',
  },
];

export const ministryAgreements: MinistryAgreement[] = [
  {
    id: 'agr-1',
    title: 'Соглашение о сотрудничестве в сфере инвестиций',
    description: 'Соглашение с Министерством инвестиций о сотрудничестве в сфере иностранных инвестиций и развития инвестиционных проектов.',
    ministryId: 'min-1',
    type: 'Соглашение',
    status: 'Действует',
    effectiveDate: '2023-06-15',
    expiryDate: '2026-06-15',
    signatories: ['Иванов И.И.', 'U Zaw Min'],
    relatedProjects: ['proj-1', 'proj-2', 'proj-3'],
    documentUrl: '/documents/investment_agreement.pdf',
  },
  {
    id: 'agr-2',
    title: 'Меморандум о взаимопонимании по органическому земледелию',
    description: 'Меморандум с Министерством сельского хозяйства о сотрудничестве в развитии органического земледелия.',
    ministryId: 'min-6',
    type: 'Меморандум',
    status: 'Действует',
    effectiveDate: '2023-09-01',
    expiryDate: '2025-09-01',
    signatories: ['Сидоров С.С.', 'U Win Pe'],
    relatedProjects: ['proj-6', 'proj-7'],
    documentUrl: '/documents/organic_farming_mou.pdf',
  },
  {
    id: 'agr-3',
    title: 'Экологическое соглашение по проекту добычи никеля',
    description: 'Соглашение с Министерством природных ресурсов об экологических стандартах при добыче никеля.',
    ministryId: 'min-3',
    type: 'Соглашение',
    status: 'Действует',
    effectiveDate: '2023-11-10',
    expiryDate: '2025-11-10',
    signatories: ['Петров П.П.', 'U Kyaw Win'],
    relatedProjects: ['proj-3'],
    documentUrl: '/documents/nickel_env_agreement.pdf',
  },
  {
    id: 'agr-4',
    title: 'Лицензия на добычу полезных ископаемых',
    description: 'Лицензия, выданная Министерством инвестиций на добычу полезных ископаемых в регионе Мандалай.',
    ministryId: 'min-1',
    type: 'Лицензия',
    status: 'Действует',
    effectiveDate: '2023-01-15',
    expiryDate: '2028-01-15',
    signatories: ['U Zaw Min'],
    relatedProjects: ['proj-2'],
    documentUrl: '/documents/mining_license.pdf',
  },
  {
    id: 'agr-5',
    title: 'Соглашение о торговом сотрудничестве',
    description: 'Соглашение с Министерством торговли о развитии торговых отношений и экспорта продукции.',
    ministryId: 'min-5',
    type: 'Соглашение',
    status: 'На подписании',
    effectiveDate: '2024-04-01',
    signatories: ['Сидоров С.С.', 'Daw Aye Aye'],
    relatedProjects: ['proj-6', 'proj-7'],
  },
  {
    id: 'agr-6',
    title: 'Разрешение на строительство энергетической инфраструктуры',
    description: 'Разрешение от Министерства энергетики на строительство энергетической инфраструктуры.',
    ministryId: 'min-4',
    type: 'Разрешение',
    status: 'Действует',
    effectiveDate: '2023-08-20',
    expiryDate: '2025-08-20',
    signatories: ['U Thein Aung'],
    relatedProjects: ['proj-5', 'proj-9'],
    documentUrl: '/documents/energy_construction_permit.pdf',
  },
  {
    id: 'agr-7',
    title: 'Правовая база для иностранных инвестиций',
    description: 'Комплекс документов по правовой базе для иностранных инвестиций в Мьянме.',
    ministryId: 'min-1',
    type: 'Правовая база',
    status: 'Действует',
    effectiveDate: '2023-01-01',
    signatories: ['U Zaw Min'],
    relatedProjects: ['proj-1', 'proj-2', 'proj-3'],
    documentUrl: '/documents/investment_legal_framework.pdf',
  },
  {
    id: 'agr-8',
    title: 'Соглашение о портовом строительстве',
    description: 'Соглашение с Министерством транспорта о строительстве грузового порта.',
    ministryId: 'min-8',
    type: 'Соглашение',
    status: 'На подписании',
    effectiveDate: '2024-05-01',
    signatories: ['U Tun Kyi'],
    relatedProjects: ['proj-8'],
  },
];