import { MiningSite } from '@/types/mining';

export const miningSites: MiningSite[] = [
  {
    id: 'mine-1',
    name: 'Месторождение "Золотой Разлом"',
    code: 'GOLD-2026',
    location: {
      lat: 23.1567,
      lng: 96.0844,
      region: 'Shan State',
      depth: 450,
    },
    minerals: [
      {
        type: 'gold',
        name: 'Золото',
        grade: 8.5,
        reserves: 125000,
        confidence: 'measured',
        extractionRate: 94.5,
        marketPrice: 65000,
      },
      {
        type: 'antimony',
        name: 'Сурьма (Sb)',
        grade: 2.3,
        reserves: 45000,
        confidence: 'indicated',
        extractionRate: 88.2,
        marketPrice: 12000,
      },
      {
        type: 'associated',
        name: 'Серебро',
        grade: 15.2,
        reserves: 8000,
        confidence: 'inferred',
        extractionRate: 85.0,
        marketPrice: 800,
      },
    ],
    currentStage: 'extraction',
    stagesProgress: {
      exploration: 100,
      drilling: 100,
      evaluation: 100,
      extraction: 78,
      processing: 65,
    },
    metrics: {
      totalReserves: 4250000,
      dailyProduction: 1250,
      gradeAverage: 7.8,
      recoveryRate: 92.3,
      stripRatio: 3.2,
      costPerTon: 28.5,
      netPresentValue: 185.4,
      internalRateOfReturn: 34.2,
      paybackPeriod: 26,
      safetyIndex: 88,
      environmentalCompliance: 92,
    },
    equipment: [
      {
        id: 'eq-1',
        name: 'Буровая установка БУ-3000',
        type: 'drill',
        status: 'active',
        efficiency: 95,
        hoursOperated: 12450,
        nextMaintenance: '2026-06-15',
      },
      {
        id: 'eq-2',
        name: 'Экскаватор ЭКГ-20',
        type: 'excavator',
        status: 'active',
        efficiency: 92,
        hoursOperated: 8900,
        nextMaintenance: '2026-05-20',
      },
      {
        id: 'eq-3',
        name: 'Самосвал БелАЗ-7513',
        type: 'truck',
        status: 'maintenance',
        efficiency: 78,
        hoursOperated: 15600,
        nextMaintenance: '2026-05-10',
      },
      {
        id: 'eq-4',
        name: 'Дробилка щековая СМД-110',
        type: 'crusher',
        status: 'active',
        efficiency: 88,
        hoursOperated: 11200,
        nextMaintenance: '2026-07-01',
      },
      {
        id: 'eq-5',
        name: 'Мельница шаровая МШР-3200',
        type: 'mill',
        status: 'active',
        efficiency: 90,
        hoursOperated: 9800,
        nextMaintenance: '2026-06-20',
      },
      {
        id: 'eq-6',
        name: 'Сепаратор магнитный ПБС-90/250',
        type: 'separator' as const,
        status: 'active',
        efficiency: 94,
        hoursOperated: 7800,
        nextMaintenance: '2026-08-10',
      },
    ],
    achievements: [
      {
        id: 'ach-1',
        title: 'Мастер бурения',
        description: 'Пробурено более 10,000 метров',
        icon: '🛠️',
        unlocked: true,
        progress: 100,
        category: 'extraction',
      },
      {
        id: 'ach-2',
        title: 'Геохимик',
        description: 'Проанализировано 500+ проб',
        icon: '🧪',
        unlocked: true,
        progress: 100,
        category: 'exploration',
      },
      {
        id: 'ach-3',
        title: 'Эффективная добыча',
        description: 'Коэффициент извлечения >90%',
        icon: '⚡',
        unlocked: true,
        progress: 100,
        category: 'efficiency',
      },
      {
        id: 'ach-4',
        title: 'Безопасность превыше всего',
        description: '365 дней без происшествий',
        icon: '🛡️',
        unlocked: false,
        progress: 72,
        category: 'safety',
      },
      {
        id: 'ach-5',
        title: 'Инноватор',
        description: 'Внедрение новой технологии',
        icon: '💡',
        unlocked: false,
        progress: 45,
        category: 'innovation',
      },
    ],
    team: [
      {
        id: 't-1',
        name: 'Иванов И.И.',
        role: 'chief_engineer',
        experience: 45,
        performance: 96,
      },
      {
        id: 't-2',
        name: 'Петров П.П.',
        role: 'geologist',
        experience: 32,
        performance: 92,
      },
      {
        id: 't-3',
        name: 'Сидоров С.С.',
        role: 'driller',
        experience: 28,
        performance: 89,
      },
    ],
    geologyData: {
      rockType: 'Гранитогнейсы, амфиболиты',
      age: 'Протерозой - Ранний палеозой',
      structure: 'Штокверковая минерализация',
      drillHoles: [
        {
          id: 'dh-1',
          name: 'Скважина №1',
          depth: 420,
          coordinates: { x: 100, y: 150 },
          minerals: [
            { depthFrom: 80, depthTo: 95, mineral: 'Au', grade: 5.2 },
            { depthFrom: 150, depthTo: 180, mineral: 'Au', grade: 12.8 },
            { depthFrom: 200, depthTo: 230, mineral: 'Sb', grade: 1.8 },
            { depthFrom: 300, depthTo: 340, mineral: 'Au', grade: 9.5 },
            { depthFrom: 380, depthTo: 420, mineral: 'Au', grade: 15.2 },
          ],
          status: 'completed',
        },
        {
          id: 'dh-2',
          name: 'Скважина №2',
          depth: 380,
          coordinates: { x: 120, y: 180 },
          minerals: [
            { depthFrom: 60, depthTo: 85, mineral: 'Au', grade: 3.8 },
            { depthFrom: 140, depthTo: 165, mineral: 'Au', grade: 8.9 },
            { depthFrom: 200, depthTo: 240, mineral: 'Sb', grade: 3.2 },
            { depthFrom: 280, depthTo: 320, mineral: 'Au', grade: 11.3 },
          ],
          status: 'completed',
        },
        {
          id: 'dh-3',
          name: 'Скважина №3',
          depth: 500,
          coordinates: { x: 90, y: 200 },
          minerals: [
            { depthFrom: 100, depthTo: 130, mineral: 'Au', grade: 6.5 },
            { depthFrom: 180, depthTo: 210, mineral: 'Au', grade: 10.2 },
            { depthFrom: 250, depthTo: 290, mineral: 'Sb', grade: 2.5 },
            { depthFrom: 350, depthTo: 400, mineral: 'Au', grade: 14.8 },
            { depthFrom: 420, depthTo: 480, mineral: 'Au', grade: 18.3 },
          ],
          status: 'drilling',
        },
      ],
      samples: [
        { id: 's-1', location: { x: 100, y: 150 }, depth: 85, gold: 5.2, antimony: 0.8 },
        { id: 's-2', location: { x: 100, y: 150 }, depth: 165, gold: 12.8, antimony: 1.2 },
        { id: 's-3', location: { x: 120, y: 180 }, depth: 75, gold: 3.8, antimony: 0.5 },
        { id: 's-4', location: { x: 120, y: 180 }, depth: 155, gold: 8.9, antimony: 1.8, beryllium: 0.3 },
        { id: 's-5', location: { x: 90, y: 200 }, depth: 105, gold: 6.5, tantalum: 0.15 },
        { id: 's-6', location: { x: 90, y: 200 }, depth: 185, gold: 10.2, antimony: 2.1, beryllium: 0.5 },
      ],
    },
  },
  {
    id: 'mine-2',
    name: 'Месторождение "Бериллиевый Хребет"',
    code: 'BERY-2026',
    location: {
      lat: 22.9833,
      lng: 96.5667,
      region: 'Shan State',
      depth: 320,
    },
    minerals: [
      {
        type: 'beryllium',
        name: 'Бериллий (Be)',
        grade: 0.85,
        reserves: 8500,
        confidence: 'indicated',
        extractionRate: 82.5,
        marketPrice: 85000,
      },
      {
        type: 'tantalum',
        name: 'Тантал (Ta)',
        grade: 0.25,
        reserves: 1200,
        confidence: 'inferred',
        extractionRate: 78.3,
        marketPrice: 450000,
      },
      {
        type: 'associated',
        name: 'Литий (Li)',
        grade: 1.2,
        reserves: 15000,
        confidence: 'inferred',
        extractionRate: 80.0,
        marketPrice: 15000,
      },
    ],
    currentStage: 'drilling',
    stagesProgress: {
      exploration: 100,
      drilling: 65,
      evaluation: 30,
      extraction: 0,
      processing: 0,
    },
    metrics: {
      totalReserves: 1250000,
      dailyProduction: 0,
      gradeAverage: 0.85,
      recoveryRate: 0,
      stripRatio: 2.8,
      costPerTon: 0,
      netPresentValue: 245.7,
      internalRateOfReturn: 42.5,
      paybackPeriod: 18,
      safetyIndex: 92,
      environmentalCompliance: 95,
    },
    equipment: [
      {
        id: 'eq-7',
        name: 'Буровая установка БУ-2000',
        type: 'drill',
        status: 'active',
        efficiency: 90,
        hoursOperated: 4500,
        nextMaintenance: '2026-05-25',
      },
      {
        id: 'eq-8',
        name: 'Экскаватор ЭКГ-10',
        type: 'excavator',
        status: 'standby',
        efficiency: 95,
        hoursOperated: 3200,
        nextMaintenance: '2026-06-10',
      },
    ],
    achievements: [
      {
        id: 'ach-6',
        title: 'Первооткрыватель',
        description: 'Открыто новое месторождение',
        icon: '🗺️',
        unlocked: true,
        progress: 100,
        category: 'exploration',
      },
      {
        id: 'ach-7',
        title: 'Мастер бурения',
        description: 'Пробурено более 10,000 метров',
        icon: '🛠️',
        unlocked: false,
        progress: 45,
        category: 'extraction',
      },
    ],
    team: [
      {
        id: 't-4',
        name: 'Козлов К.К.',
        role: 'chief_engineer',
        experience: 38,
        performance: 94,
      },
      {
        id: 't-5',
        name: 'Морозова М.М.',
        role: 'geologist',
        experience: 25,
        performance: 90,
      },
    ],
    geologyData: {
      rockType: 'Пегматиты, гранитные купола',
      age: 'Поздний архей - Ранний протерозой',
      structure: 'Жильная минерализация',
      drillHoles: [
        {
          id: 'dh-4',
          name: 'Скважина Б-1',
          depth: 280,
          coordinates: { x: 200, y: 250 },
          minerals: [
            { depthFrom: 50, depthTo: 80, mineral: 'Be', grade: 0.5 },
            { depthFrom: 120, depthTo: 160, mineral: 'Be', grade: 1.2 },
            { depthFrom: 180, depthTo: 220, mineral: 'Ta', grade: 0.18 },
            { depthFrom: 240, depthTo: 280, mineral: 'Be', grade: 0.9 },
          ],
          status: 'completed',
        },
        {
          id: 'dh-5',
          name: 'Скважина Б-2',
          depth: 320,
          coordinates: { x: 220, y: 280 },
          minerals: [
            { depthFrom: 60, depthTo: 100, mineral: 'Be', grade: 0.7 },
            { depthFrom: 140, depthTo: 180, mineral: 'Be', grade: 1.5 },
            { depthFrom: 200, depthTo: 240, mineral: 'Ta', grade: 0.32 },
            { depthFrom: 260, depthTo: 300, mineral: 'Be', grade: 0.95 },
          ],
          status: 'drilling',
        },
      ],
      samples: [
        { id: 's-7', location: { x: 200, y: 250 }, depth: 65, beryllium: 0.5, tantalum: 0.05 },
        { id: 's-8', location: { x: 200, y: 250 }, depth: 145, beryllium: 1.2, tantalum: 0.12 },
        { id: 's-9', location: { x: 220, y: 280 }, depth: 75, beryllium: 0.7, tantalum: 0.08 },
        { id: 's-10', location: { x: 220, y: 280 }, depth: 165, beryllium: 1.5, tantalum: 0.32 },
      ],
    },
  },
  {
    id: 'mine-3',
    name: 'Месторождение "Сурьмяные Горы"',
    code: 'ANT-2026',
    location: {
      lat: 23.25,
      lng: 95.9167,
      region: 'Sagaing Region',
      depth: 280,
    },
    minerals: [
      {
        type: 'antimony',
        name: 'Сурьма (Sb)',
        grade: 4.8,
        reserves: 78000,
        confidence: 'measured',
        extractionRate: 91.3,
        marketPrice: 12000,
      },
      {
        type: 'gold',
        name: 'Золото',
        grade: 2.3,
        reserves: 35000,
        confidence: 'indicated',
        extractionRate: 88.5,
        marketPrice: 65000,
      },
      {
        type: 'tantalum',
        name: 'Тантал (Ta)',
        grade: 0.18,
        reserves: 800,
        confidence: 'inferred',
        extractionRate: 75.0,
        marketPrice: 450000,
      },
    ],
    currentStage: 'evaluation',
    stagesProgress: {
      exploration: 100,
      drilling: 100,
      evaluation: 85,
      extraction: 0,
      processing: 0,
    },
    metrics: {
      totalReserves: 2850000,
      dailyProduction: 0,
      gradeAverage: 4.2,
      recoveryRate: 0,
      stripRatio: 2.1,
      costPerTon: 0,
      netPresentValue: 145.3,
      internalRateOfReturn: 38.7,
      paybackPeriod: 22,
      safetyIndex: 85,
      environmentalCompliance: 88,
    },
    equipment: [
      {
        id: 'eq-9',
        name: 'Буровая установка БУ-1500',
        type: 'drill',
        status: 'active',
        efficiency: 88,
        hoursOperated: 6800,
        nextMaintenance: '2026-06-05',
      },
    ],
    achievements: [
      {
        id: 'ach-8',
        title: 'Аналитик',
        description: 'Составлен детальный отчет',
        icon: '📊',
        unlocked: true,
        progress: 100,
        category: 'exploration',
      },
    ],
    team: [
      {
        id: 't-6',
        name: 'Новиков Н.Н.',
        role: 'chief_engineer',
        experience: 40,
        performance: 92,
      },
      {
        id: 't-7',
        name: 'Орлова О.О.',
        role: 'geologist',
        experience: 28,
        performance: 88,
      },
    ],
    geologyData: {
      rockType: 'Кремнистые сланцы, кварциты',
      age: 'Палеозой - Мезозой',
      structure: 'Стратиформные залежи',
      drillHoles: [
        {
          id: 'dh-6',
          name: 'Скважина С-1',
          depth: 250,
          coordinates: { x: 300, y: 350 },
          minerals: [
            { depthFrom: 40, depthTo: 70, mineral: 'Sb', grade: 3.2 },
            { depthFrom: 100, depthTo: 140, mineral: 'Sb', grade: 6.8 },
            { depthFrom: 160, depthTo: 200, mineral: 'Au', grade: 1.8 },
            { depthFrom: 220, depthTo: 250, mineral: 'Sb', grade: 5.5 },
          ],
          status: 'completed',
        },
      ],
      samples: [
        { id: 's-11', location: { x: 300, y: 350 }, depth: 55, antimony: 3.2, gold: 0.8 },
        { id: 's-12', location: { x: 300, y: 350 }, depth: 125, antimony: 6.8, gold: 2.3 },
        { id: 's-13', location: { x: 300, y: 350 }, depth: 185, antimony: 2.1, gold: 1.8, tantalum: 0.15 },
      ],
    },
  },
];