import {
  CountryRiskSnapshot,
  PoliticalEvent,
  EconomicIndicator,
  SourceRecord,
  ProjectExposure,
  RiskAlert,
  AIInsight,
  DecisionLogEntry,
  VerificationRecord,
} from '@/types/myanmar-intelligence';

// =====================================================
// ИСТОЧНИКИ ДАННЫХ
// =====================================================

export const sources: SourceRecord[] = [
  {
    id: 'src-1',
    name: 'Министерство информации Мьянмы',
    type: 'Государственный',
    publishDate: '2026-04-05',
    receiveDate: '2026-04-05',
    region: 'Нейпьидо',
    topic: 'Политическая ситуация',
    reliability: 'B',
    credibility: '2',
    verificationStatus: 'Подтверждено',
    independentConfirmations: 3,
    url: 'https://example.gov.mm',
    internalNotes: 'Официальный источник, данные согласуются с международными наблюдателями',
    tag: 'Факт',
    analystId: 'user-1',
  },
  {
    id: 'src-2',
    name: 'Reuters Myanmar Bureau',
    type: 'СМИ',
    publishDate: '2026-04-04',
    receiveDate: '2026-04-04',
    region: 'Янгон',
    topic: 'Экономические реформы',
    reliability: 'A',
    credibility: '1',
    verificationStatus: 'Подтверждено',
    independentConfirmations: 5,
    url: 'https://reuters.com',
    internalNotes: 'Проверенное международное агентство',
    tag: 'Факт',
    analystId: 'user-2',
  },
  {
    id: 'src-3',
    name: 'Myanmar Now',
    type: 'СМИ',
    publishDate: '2026-04-03',
    receiveDate: '2026-04-03',
    region: 'Штат Шан',
    topic: 'Конфликт в северных штатах',
    reliability: 'B',
    credibility: '2',
    verificationStatus: 'Частично подтверждено',
    independentConfirmations: 2,
    internalNotes: 'Независимое издание, требуется дополнительная верификация',
    tag: 'Аналитика',
    analystId: 'user-1',
  },
  {
    id: 'src-4',
    name: 'World Bank Myanmar',
    type: 'Международная организация',
    publishDate: '2026-04-01',
    receiveDate: '2026-04-02',
    region: 'Национальный',
    topic: 'Макроэкономические показатели',
    reliability: 'A',
    credibility: '1',
    verificationStatus: 'Подтверждено',
    independentConfirmations: 4,
    url: 'https://worldbank.org/mm',
    internalNotes: 'Официальные данные Всемирного банка',
    tag: 'Факт',
    analystId: 'user-3',
  },
  {
    id: 'src-5',
    name: 'Аналитический отдел РК',
    type: 'Коммерческий',
    publishDate: '2026-04-06',
    receiveDate: '2026-04-06',
    region: 'Национальный',
    topic: 'Оценка рисков проектов',
    reliability: 'B',
    credibility: '2',
    verificationStatus: 'Подтверждено',
    independentConfirmations: 1,
    internalNotes: 'Внутренний анализ на основе мульти-источников',
    tag: 'Аналитика',
    analystId: 'user-1',
  },
  {
    id: 'src-6',
    name: 'UN OCHA Myanmar',
    type: 'Международная организация',
    publishDate: '2026-03-28',
    receiveDate: '2026-03-29',
    region: 'Штат Ракхайн',
    topic: 'Гуманитарная ситуация',
    reliability: 'A',
    credibility: '1',
    verificationStatus: 'Подтверждено',
    independentConfirmations: 6,
    url: 'https://ocha.mm',
    internalNotes: 'Высоконадежный источник по гуманитарным вопросам',
    tag: 'Факт',
    analystId: 'user-2',
  },
  {
    id: 'src-7',
    name: 'Local contacts network',
    type: 'Разведывательный',
    publishDate: '2026-04-05',
    receiveDate: '2026-04-05',
    region: 'Мандалай',
    topic: 'Операционная доступность',
    reliability: 'C',
    credibility: '3',
    verificationStatus: 'Требует верификации',
    independentConfirmations: 0,
    internalNotes: 'Информация от местных контактов, ожидаем подтверждения',
    tag: 'Предупреждение',
    analystId: 'user-1',
  },
  {
    id: 'src-8',
    name: 'IMF Article IV Consultation',
    type: 'Международная организация',
    publishDate: '2026-03-15',
    receiveDate: '2026-03-16',
    region: 'Национальный',
    topic: 'Валютная политика',
    reliability: 'A',
    credibility: '1',
    verificationStatus: 'Подтверждено',
    independentConfirmations: 3,
    url: 'https://imf.org/mm',
    internalNotes: 'Официальный отчет МВФ',
    tag: 'Факт',
    analystId: 'user-3',
  },
];

// =====================================================
// СНИМОК РИСКОВ СТРАНЫ
// =====================================================

export const countryRiskSnapshot: CountryRiskSnapshot = {
  id: 'snapshot-1',
  timestamp: '2026-04-06T12:00:00Z',
  country: 'Мьянма',
  overallRisk: 'Высокий',
  politicalStability: 35,
  conflictIntensity: 62,
  operationalAccessibility: 58,
  logisticalRisk: 45,
  currencyMacroRisk: 71,
  openAlerts: 7,
  affectedProjects: 8,
  lastUpdate: '2026-04-06T10:30:00Z',
  analystSummary: 'Ситуация в Мьянме остается нестабильной. Продолжаются вооруженные столкновения в северных штатах. Валютный рынок демонстрирует повышенную волатильность. Рекомендуется усилить мониторинг проектов в регионах с высоким конфликтным потенциалом.',
  weeklyChanges: [
    {
      indicator: 'Политическая стабильность',
      previousValue: 40,
      currentValue: 35,
      change: -5,
      trend: 'down',
      significance: 'high',
    },
    {
      indicator: 'Интенсивность конфликтов',
      previousValue: 55,
      currentValue: 62,
      change: 7,
      trend: 'up',
      significance: 'high',
    },
    {
      indicator: 'Курс MMK/USD',
      previousValue: 2100,
      currentValue: 2180,
      change: 3.8,
      trend: 'up',
      significance: 'medium',
    },
    {
      indicator: 'Операционная доступность',
      previousValue: 65,
      currentValue: 58,
      change: -7,
      trend: 'down',
      significance: 'high',
    },
    {
      indicator: 'Логистический риск',
      previousValue: 42,
      currentValue: 45,
      change: 3,
      trend: 'up',
      significance: 'low',
    },
  ],
  keySignals: [
    {
      id: 'signal-1',
      title: 'Эскалация конфликта в штате Шан',
      description: 'Зафиксировано усиление вооруженных столкновений между армией и этническими вооруженными группировками в северной части штата.',
      severity: 'Критический',
      timestamp: '2026-04-05T08:00:00Z',
      source: 'Myanmar Now + подтверждение от UN OCHA',
      verified: true,
    },
    {
      id: 'signal-2',
      title: 'Девальвация национальной валюты',
      description: 'Кьят потерял 3.8% к доллару за неделю. Центробанк предпринимает интервенции, но эффект ограничен.',
      severity: 'Высокий',
      timestamp: '2026-04-04T14:00:00Z',
      source: 'IMF + Reuters',
      verified: true,
    },
    {
      id: 'signal-3',
      title: 'Задержки в таможенном оформлении',
      description: 'Увеличение времени таможенного оформления импорта до 14 дней. Причина - усиление проверок безопасности.',
      severity: 'Средний',
      timestamp: '2026-04-03T10:00:00Z',
      source: 'Local contacts network',
      verified: false,
    },
  ],
};

// =====================================================
// ПОЛИТИЧЕСКИЕ СОБЫТИЯ
// =====================================================

export const politicalEvents: PoliticalEvent[] = [
  {
    id: 'pe-1',
    type: 'Военный конфликт',
    title: 'Обострение ситуации в штате Шан',
    description: 'Эскалация вооруженных столкновений между Tatmadaw и TNLA в северном Шане. Захвачено несколько стратегических позиций.',
    timestamp: '2026-04-05T08:00:00Z',
    region: 'Штат Шан',
    actors: ['Tatmadaw', 'TNLA', 'MNDAA'],
    impact: 'Критический',
    verificationStatus: 'Подтверждено',
    sources: [sources[2], sources[5]],
    aiInterpretation: 'Эскалация конфликта может привести к нарушению логистических маршрутов в северных регионах. Проекты в зоне влияния требуют немедленного пересмотра планов безопасности.',
    confirmedFacts: [
      'Столкновения зафиксированы независимыми источниками',
      'Заблокированы ключевые дороги в регионе',
      'Имеются пострадавшие среди гражданского населения',
    ],
    disputedSignals: [
      'Точные масштабы потерь неизвестны',
      'Неподтверждены данные о захвате новых территорий',
    ],
  },
  {
    id: 'pe-2',
    type: 'Санкции',
    title: 'Расширение санкционного списка ЕС',
    description: 'Европейский союз добавил 12 новых физических и юридических лиц в санкционный список, связанных с военными структурами.',
    timestamp: '2026-04-04T16:00:00Z',
    region: 'Национальный',
    actors: ['ЕС', 'Военная хунта'],
    impact: 'Высокий',
    verificationStatus: 'Подтверждено',
    sources: [sources[1]],
    aiInterpretation: 'Новые санкции могут затронуть цепочки поставок для проектов, использующих подрядчиков из списка. Рекомендуется провести аудит контрагентов.',
    confirmedFacts: [
      'Официальная публикация в журнале ЕС',
      'Список включает ключевые военные предприятия',
    ],
    disputedSignals: [],
  },
  {
    id: 'pe-3',
    type: 'Переговоры',
    title: 'Межбирманские консультации в Куньмине',
    description: 'Представители военного правительства и оппозиции встретились в Китае для обсуждения возможного прекращения огня.',
    timestamp: '2026-04-02T12:00:00Z',
    region: 'Национальный',
    actors: ['SAC', 'NUG', 'Китай'],
    impact: 'Средний',
    verificationStatus: 'Частично подтверждено',
    sources: [sources[0], sources[2]],
    aiInterpretation: 'Переговоры указывают на возможное ослабление напряженности, однако конкретные результаты пока не достигнуты.',
    confirmedFacts: [
      'Встреча состоялась',
      'Участвовали представители обеих сторон',
    ],
    disputedSignals: [
      'Содержание переговоров не раскрывается',
      'Неясны перспективы достижения соглашения',
    ],
  },
  {
    id: 'pe-4',
    type: 'Протест',
    title: 'Акции протеста в Мандалае',
    description: 'Массовые мирные протесты против роста цен на продовольствие. Участие приняли около 5000 человек.',
    timestamp: '2026-03-30T09:00:00Z',
    region: 'Мандалай',
    actors: ['Гражданское население', 'Полиция'],
    impact: 'Средний',
    verificationStatus: 'Подтверждено',
    sources: [sources[2], sources[6]],
    aiInterpretation: 'Протесты отражают растущее социальное напряжение из-за экономических трудностей. Возможны перебои в работе предприятий в регионе.',
    confirmedFacts: [
      'Протесты зафиксированы несколькими источниками',
      'Протесты носили мирный характер',
    ],
    disputedSignals: [
      'Точное число участников',
    ],
  },
];

// =====================================================
// ЭКОНОМИЧЕСКИЕ ИНДИКАТОРЫ
// =====================================================

export const economicIndicators: EconomicIndicator[] = [
  {
    id: 'ei-1',
    type: 'Курс валюты',
    name: 'MMK/USD',
    value: 2180,
    unit: 'MMK за 1 USD',
    previousValue: 2100,
    changePercent: 3.8,
    timestamp: '2026-04-06T00:00:00Z',
    forecast: 2250,
    impactOnProjects: 'Удорожание импорта оборудования и материалов. Увеличение себестоимости проектов на 4-6%.',
    verificationStatus: 'Подтверждено',
    source: sources[7],
  },
  {
    id: 'ei-2',
    type: 'Инфляция',
    name: 'Потребительская инфляция',
    value: 18.5,
    unit: '% годовых',
    previousValue: 16.2,
    changePercent: 14.2,
    timestamp: '2026-03-31T00:00:00Z',
    forecast: 20.0,
    impactOnProjects: 'Рост операционных расходов. Необходимость пересмотра бюджетов проектов.',
    verificationStatus: 'Подтверждено',
    source: sources[3],
  },
  {
    id: 'ei-3',
    type: 'ВВП',
    name: 'Рост ВВП',
    value: 1.2,
    unit: '%',
    previousValue: 2.8,
    changePercent: -57.1,
    timestamp: '2026-03-31T00:00:00Z',
    forecast: 0.8,
    impactOnProjects: 'Замедление экономики снижает спрос на внутреннем рынке. Экспортные проекты менее уязвимы.',
    verificationStatus: 'Подтверждено',
    source: sources[3],
  },
  {
    id: 'ei-4',
    type: 'Торговый баланс',
    name: 'Торговый дефицит',
    value: -2.8,
    unit: 'млрд USD',
    previousValue: -2.3,
    changePercent: 21.7,
    timestamp: '2026-02-28T00:00:00Z',
    forecast: -3.1,
    impactOnProjects: 'Давление на валютный курс продолжится. Рекомендуется хеджирование валютных рисков.',
    verificationStatus: 'Подтверждено',
    source: sources[3],
  },
  {
    id: 'ei-5',
    type: 'Добыча ресурсов',
    name: 'Добыча никеля',
    value: 42000,
    unit: 'тонн/год',
    previousValue: 45000,
    changePercent: -6.7,
    timestamp: '2026-03-31T00:00:00Z',
    forecast: 40000,
    impactOnProjects: 'Снижение добычи из-за конфликтов в регионах. Проект TTN-2026 под угрозой.',
    verificationStatus: 'Частично подтверждено',
    source: sources[4],
  },
  {
    id: 'ei-6',
    type: 'Инвестиции',
    name: 'Прямые иностранные инвестиции',
    value: 1.8,
    unit: 'млрд USD',
    previousValue: 2.4,
    changePercent: -25.0,
    timestamp: '2026-03-31T00:00:00Z',
    forecast: 1.5,
    impactOnProjects: 'Снижение доверия инвесторов. Новые проекты могут столкнуться с трудностями финансирования.',
    verificationStatus: 'Подтверждено',
    source: sources[3],
  },
];

// =====================================================
// ВОЗДЕЙСТВИЕ НА ПРОЕКТЫ
// =====================================================

export const projectExposures: ProjectExposure[] = [
  {
    id: 'pe-1',
    projectId: 'proj-1',
    projectName: 'Завод удобрений в Нейпьидо',
    projectCode: 'MFR-2026',
    region: 'Naypyidaw Region',
    industry: 'Производство',
    currentRiskScore: 58,
    riskChange7d: 5,
    riskChange30d: 12,
    impactTypes: ['Макроэкономический', 'Регуляторный'],
    recommendedAction: 'Ускорить закупку импортного оборудования до дальнейшей девальвации. Рассмотреть возможность локализации части поставок.',
    decisionStatus: 'Ожидает',
    decisionOwner: 'Руководитель департамента',
    lastReviewDate: '2026-04-05',
    affectedMilestones: ['Запуск производства', 'Получение сертификатов'],
    mitigationPlan: 'Досрочное заключение контрактов с поставщиками по фиксированным ценам',
  },
  {
    id: 'pe-2',
    projectId: 'proj-2',
    projectName: 'Геологоразведка и добыча РЗМ',
    projectCode: 'TTN-2026',
    region: 'Shan State',
    industry: 'Добыча',
    currentRiskScore: 82,
    riskChange7d: 18,
    riskChange30d: 25,
    impactTypes: ['Политический', 'Логистический', 'Контрагентский'],
    recommendedAction: 'Приостановить работы в северной части месторождения. Усилить меры безопасности. Пересмотреть сроки реализации.',
    decisionStatus: 'Ожидает',
    decisionOwner: 'Руководитель проекта',
    lastReviewDate: '2026-04-06',
    affectedMilestones: ['Строительство инфраструктуры', 'Начало промышленной добычи'],
    mitigationPlan: 'Перенос работ в безопасные зоны, усиление охраны объектов',
  },
  {
    id: 'pe-3',
    projectId: 'proj-3',
    projectName: 'Торговый дом',
    projectCode: 'BWD-2026',
    region: 'Yangon Region',
    industry: 'Инфраструктура',
    currentRiskScore: 65,
    riskChange7d: 8,
    riskChange30d: 15,
    impactTypes: ['Логистический', 'Макроэкономический'],
    recommendedAction: 'Оптимизировать маршруты поставок в обход конфликтных зон. Рассмотреть альтернативные порты.',
    decisionStatus: 'Подтверждено',
    decisionOwner: 'Руководитель департамента',
    lastReviewDate: '2026-04-04',
    affectedMilestones: ['Экспорт товаров', 'Запуск новых линий логистики'],
  },
  {
    id: 'pe-4',
    projectId: 'proj-9',
    projectName: 'Cement Plant Upgrade',
    projectCode: 'CPU-2026',
    region: 'Rakhine State',
    industry: 'Инфраструктура',
    currentRiskScore: 75,
    riskChange7d: 10,
    riskChange30d: 20,
    impactTypes: ['Политический', 'Контрагентский'],
    recommendedAction: 'Ускорить демонтаж старого оборудования до возможного обострения ситуации. Найти альтернативных подрядчиков.',
    decisionStatus: 'Ожидает',
    lastReviewDate: '2026-04-03',
    affectedMilestones: ['Демонтаж старого оборудования', 'Установка и запуск'],
  },
  {
    id: 'pe-5',
    projectId: 'proj-5',
    projectName: 'Завод удобрений Иеравади',
    projectCode: 'YPL-2026',
    region: 'Yangon Region',
    industry: 'Инфраструктура',
    currentRiskScore: 45,
    riskChange7d: 3,
    riskChange30d: 8,
    impactTypes: ['Макроэкономический'],
    recommendedAction: 'Продолжить реализацию с учетом валютных рисков. Рассмотреть возможность привлечения местного финансирования.',
    decisionStatus: 'Подтверждено',
    decisionOwner: 'Руководитель проекта',
    lastReviewDate: '2026-04-02',
    affectedMilestones: [],
  },
];

// =====================================================
// РИСК-АЛЕРТЫ
// =====================================================

export const riskAlerts: RiskAlert[] = [
  {
    id: 'alert-1',
    title: 'Критическое обострение в штате Шан',
    description: 'Вооруженные столкновения непосредственно угрожают объектам проекта TTN-2026. Необходима немедленная эвакуация персонала.',
    severity: 'Критический',
    category: 'Безопасность',
    region: 'Shan State',
    timestamp: '2026-04-05T08:00:00Z',
    source: sources[2],
    affectedProjects: ['proj-2'],
    escalationLevel: 5,
    acknowledged: true,
    acknowledgedBy: 'user-1',
    acknowledgedAt: '2026-04-05T09:15:00Z',
    expiresAt: '2026-04-12T08:00:00Z',
  },
  {
    id: 'alert-2',
    title: 'Девальвация кьята превысила прогноз',
    description: 'Курс MMK/USD достиг 2180, что превышает плановый показатель на 8%. Риски превышения бюджета проектов.',
    severity: 'Высокий',
    category: 'Валютный риск',
    region: 'Национальный',
    timestamp: '2026-04-04T14:00:00Z',
    source: sources[7],
    affectedProjects: ['proj-1', 'proj-3', 'proj-5', 'proj-9'],
    escalationLevel: 4,
    acknowledged: true,
    acknowledgedBy: 'user-3',
    acknowledgedAt: '2026-04-04T15:30:00Z',
    expiresAt: '2026-04-18T14:00:00Z',
  },
  {
    id: 'alert-3',
    title: 'Задержка таможенного оформления',
    description: 'Среднее время таможенного оформления увеличилось до 14 дней. Задержки в поставках оборудования для проектов.',
    severity: 'Средний',
    category: 'Логистика',
    region: 'Yangon Region',
    timestamp: '2026-04-03T10:00:00Z',
    source: sources[6],
    affectedProjects: ['proj-1', 'proj-5'],
    escalationLevel: 3,
    acknowledged: false,
  },
  {
    id: 'alert-4',
    title: 'Риск нарушения контрактных обязательств',
    description: 'Задержки в строительстве могут привести к штрафным санкциям по контрактам с государственными организациями.',
    severity: 'Высокий',
    category: 'Контрактный риск',
    region: 'Rakhine State',
    timestamp: '2026-04-02T16:00:00Z',
    source: sources[4],
    affectedProjects: ['proj-9'],
    escalationLevel: 4,
    acknowledged: true,
    acknowledgedBy: 'user-4',
    acknowledgedAt: '2026-04-02T17:00:00Z',
  },
  {
    id: 'alert-5',
    title: 'Рост инфляции операционных расходов',
    description: 'Инфляция достигла 18.5% годовых. Операционные расходы проектов превышают плановые показатели на 12%.',
    severity: 'Высокий',
    category: 'Финансовый риск',
    region: 'Национальный',
    timestamp: '2026-04-01T12:00:00Z',
    source: sources[3],
    affectedProjects: ['proj-1', 'proj-2', 'proj-3', 'proj-5', 'proj-9'],
    escalationLevel: 4,
    acknowledged: true,
    acknowledgedBy: 'user-1',
    acknowledgedAt: '2026-04-01T14:00:00Z',
  },
  {
    id: 'alert-6',
    title: 'Обновление санкционных списков ЕС',
    description: 'Новые санкции могут затронуть подрядчиков проектов. Требуется проверка контрагентской базы.',
    severity: 'Средний',
    category: 'Регуляторный риск',
    region: 'Национальный',
    timestamp: '2026-04-04T16:00:00Z',
    source: sources[1],
    affectedProjects: ['proj-1', 'proj-2', 'proj-9'],
    escalationLevel: 3,
    acknowledged: false,
  },
  {
    id: 'alert-7',
    title: 'Снижение операционной доступности регионов',
    description: 'Индекс операционной доступности снизился до 58. Ухудшение условий для ведения бизнеса в отдельных регионах.',
    severity: 'Средний',
    category: 'Операционный риск',
    region: 'Shan State',
    timestamp: '2026-04-05T12:00:00Z',
    source: sources[4],
    affectedProjects: ['proj-2', 'proj-6'],
    escalationLevel: 3,
    acknowledged: false,
  },
];

// =====================================================
// AI-ИНСАЙТЫ
// =====================================================

export const aiInsights: AIInsight[] = [
  {
    id: 'ai-1',
    title: 'Паттерн валютной дестабилизации',
    description: 'Анализ исторических данных указывает на возможное ускорение девальвации кьята в ближайшие 30 дней.',
    confidence: 72,
    category: 'Макроэкономика',
    timestamp: '2026-04-06T08:00:00Z',
    basedOnSources: ['src-2', 'src-4', 'src-8'],
    hypothesis: 'Сочетание снижения экспортных поступлений и оттока иностранного капитала создает предпосылки для более резкой девальвации.',
    supportingEvidence: [
      'Снижение экспорта на 15% за квартал',
      'Отток ПИИ на 25% г/г',
      'Исторический паттерн: аналогичные условия в 2021-2022 привели к девальвации на 40%',
    ],
    contradictingEvidence: [
      'Центробанк активно проводит интервенции',
      'Поддержка со стороны Китая может стабилизировать курс',
    ],
    recommendedActions: [
      'Ускорить конвертацию долларовых средств в оборудование',
      'Зафиксировать контрактные цены в долларах',
      'Рассмотреть возможность привлечения местного финансирования',
    ],
    humanReviewRequired: true,
    reviewStatus: 'Ожидает',
  },
  {
    id: 'ai-2',
    title: 'Корреляция конфликтов и логистических задержек',
    description: 'Выявлена сильная корреляция между интенсивностью конфликтов и задержками в логистике.',
    confidence: 85,
    category: 'Логистика',
    timestamp: '2026-04-05T14:00:00Z',
    basedOnSources: ['src-3', 'src-6', 'src-7'],
    hypothesis: 'Каждое увеличение индекса конфликтности на 10 пунктов приводит к увеличению логистических задержек на 3-5 дней.',
    supportingEvidence: [
      'Статистический анализ за последние 2 года',
      'Корреляция 0.78 между индексами',
      'Прямые свидетельства от логистических партнеров',
    ],
    contradictingEvidence: [
      'Некоторые маршруты остаются стабильными независимо от конфликтов',
    ],
    recommendedActions: [
      'Разработать альтернативные маршруты в обход конфликтных зон',
      'Создать буферные запасы критичных материалов',
      'Установить прямые контакты с местными логистическими операторами',
    ],
    humanReviewRequired: false,
    reviewStatus: 'Принято',
  },
  {
    id: 'ai-3',
    title: 'Окно возможностей для проектов в Янгоне',
    description: 'Янгон демонстрирует относительную стабильность по сравнению с другими регионами.',
    confidence: 68,
    category: 'Региональный анализ',
    timestamp: '2026-04-04T10:00:00Z',
    basedOnSources: ['src-1', 'src-5'],
    hypothesis: 'Янгон остается наиболее предсказуемым регионом для инвестиций благодаря развитой инфраструктуре и относительной политической стабильности.',
    supportingEvidence: [
      'Индекс операционной доступности Янгона: 72 (средний по стране: 58)',
      'Отсутствие серьезных инцидентов за последние 6 месяцев',
      'Развитая логистическая инфраструктура порта',
    ],
    contradictingEvidence: [
      'Протестные настроения в связи с ростом цен',
      'Общий тренд на ухудшение экономической ситуации',
    ],
    recommendedActions: [
      'Рассмотреть перенос приоритетных операций в Янгон',
      'Ускорить реализацию проектов в регионе',
      'Усилить мониторинг социальной напряженности',
    ],
    humanReviewRequired: true,
    reviewStatus: 'Ожидает',
  },
];

// =====================================================
// ЖУРНАЛ РЕШЕНИЙ
// =====================================================

export const decisionLog: DecisionLogEntry[] = [
  {
    id: 'dl-1',
    timestamp: '2026-04-06T09:00:00Z',
    signal: 'Критическое обострение в штате Шан угрожает проекту TTN-2026',
    aiRecommendation: 'Приостановить работы в северной части месторождения. Эвакуировать персонал из зоны риска.',
    decidedBy: 'Александр Петров (Руководитель департамента)',
    decision: 'Подтверждено',
    decisionDate: '2026-04-06T10:30:00Z',
    comments: 'Одобрена приостановка работ. Персонал переводится в Янгонский офис. Работы возобновятся после нормализации ситуации.',
    affectedProjects: ['proj-2'],
    riskScoreChanged: true,
    previousRiskScore: 64,
    newRiskScore: '82',
    reevaluated: false,
    modelVersion: 'v2.3.1',
  },
  {
    id: 'dl-2',
    timestamp: '2026-04-05T14:00:00Z',
    signal: 'Девальвация кьята превысила прогнозный уровень',
    aiRecommendation: 'Ускорить закупку импортного оборудования для проекта MFR-2026. Рассмотреть хеджирование валютных рисков.',
    decidedBy: 'Мария Сидорова (Финансовый директор)',
    decision: 'Подтверждено',
    decisionDate: '2026-04-05T16:00:00Z',
    comments: 'Одобрена досрочная закупка оборудования на $1.2M. Начаты переговоры с банком о форвардных контрактах.',
    affectedProjects: ['proj-1'],
    riskScoreChanged: true,
    previousRiskScore: 53,
    newRiskScore: '58',
    reevaluated: false,
    modelVersion: 'v2.3.1',
  },
  {
    id: 'dl-3',
    timestamp: '2026-04-04T11:00:00Z',
    signal: 'AI рекомендует перенос операций в Янгон',
    aiRecommendation: 'Янгон демонстрирует лучшие операционные условия. Рекомендуется приоритизировать проекты в этом регионе.',
    decidedBy: undefined,
    decision: 'Ожидает',
    affectedProjects: ['proj-1', 'proj-5'],
    riskScoreChanged: false,
    reevaluated: false,
    modelVersion: 'v2.3.1',
  },
  {
    id: 'dl-4',
    timestamp: '2026-04-03T09:00:00Z',
    signal: 'Задержки таможенного оформления могут повлиять на сроки проекта YPL-2026',
    aiRecommendation: 'Запустить параллельный процесс таможенного оформления через альтернативные каналы.',
    decidedBy: 'Иван Козлов (Руководитель проекта)',
    decision: 'Подтверждено',
    decisionDate: '2026-04-03T14:00:00Z',
    comments: 'Привлечена дополнительная таможенная компания. Ожидаем сокращения задержек на 30%.',
    affectedProjects: ['proj-5'],
    riskScoreChanged: false,
    reevaluated: false,
    modelVersion: 'v2.3.0',
  },
  {
    id: 'dl-5',
    timestamp: '2026-04-02T15:00:00Z',
    signal: 'Рост инфляции требует пересмотра бюджетов проектов',
    aiRecommendation: 'Инициировать пересмотр бюджетов всех активных проектов с учетом инфляционных ожиданий.',
    decidedBy: 'Мария Сидорова (Финансовый директор)',
    decision: 'Подтверждено',
    decisionDate: '2026-04-02T17:00:00Z',
    comments: 'Создана рабочая группа по пересмотру бюджетов. Планируется завершение анализа к 15 апреля.',
    affectedProjects: ['proj-1', 'proj-2', 'proj-3', 'proj-5', 'proj-9'],
    riskScoreChanged: false,
    reevaluated: true,
    modelVersion: 'v2.3.0',
  },
  {
    id: 'dl-6',
    timestamp: '2026-04-01T10:00:00Z',
    signal: 'Снижение операционной доступности в регионе Shan State',
    aiRecommendation: 'Усилить меры безопасности на объектах. Рассмотреть возможность временного персонала из других регионов.',
    decidedBy: 'Александр Петров (Руководитель департамента)',
    decision: 'Отклонено',
    decisionDate: '2026-04-01T12:00:00Z',
    comments: 'Текущие меры безопасности достаточны. Дополнительные расходы нецелесообразны на данном этапе.',
    affectedProjects: ['proj-2'],
    riskScoreChanged: false,
    reevaluated: true,
    modelVersion: 'v2.2.9',
  },
];

// =====================================================
// ЗАПИСИ ВЕРИФИКАЦИИ
// =====================================================

export const verificationRecords: VerificationRecord[] = [
  {
    id: 'vr-1',
    sourceId: 'src-1',
    verifiedBy: 'user-1',
    verificationDate: '2026-04-05T14:00:00Z',
    status: 'Подтверждено',
    confidence: 95,
    notes: 'Данные согласуются с международными источниками',
  },
  {
    id: 'vr-2',
    sourceId: 'src-3',
    verifiedBy: 'user-2',
    verificationDate: '2026-04-04T10:00:00Z',
    status: 'Частично подтверждено',
    confidence: 70,
    notes: 'Основные факты подтверждены, но детали требуют дополнительной проверки',
    conflictingSources: ['src-1'],
  },
  {
    id: 'vr-3',
    sourceId: 'src-7',
    verifiedBy: 'user-1',
    verificationDate: '2026-04-05T16:00:00Z',
    status: 'Требует верификации',
    confidence: 40,
    notes: 'Информация от единственного источника. Ожидаем подтверждения из независимых каналов.',
  },
];

// =====================================================
// ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ
// =====================================================

export function getRiskLevelColor(level: string): string {
  const colors: Record<string, string> = {
    'Критический': 'bg-red-100 text-red-800 border-red-200',
    'Высокий': 'bg-orange-100 text-orange-800 border-orange-200',
    'Средний': 'bg-amber-100 text-amber-800 border-amber-200',
    'Низкий': 'bg-green-100 text-green-800 border-green-200',
    'Минимальный': 'bg-slate-100 text-slate-800 border-slate-200',
  };
  return colors[level] || colors['Средний'];
}

export function getVerificationStatusColor(status: string): string {
  const colors: Record<string, string> = {
    'Подтверждено': 'bg-green-100 text-green-800',
    'Частично подтверждено': 'bg-blue-100 text-blue-800',
    'Требует верификации': 'bg-amber-100 text-amber-800',
    'Противоречивые сигналы': 'bg-purple-100 text-purple-800',
    'Устарело': 'bg-slate-100 text-slate-700',
    'Архив': 'bg-gray-100 text-gray-600',
  };
  return colors[status] || colors['Требует верификации'];
}

export function getSourceReliabilityColor(reliability: string): string {
  const colors: Record<string, string> = {
    'A': 'bg-green-500',
    'B': 'bg-blue-500',
    'C': 'bg-amber-500',
    'D': 'bg-orange-500',
    'E': 'bg-red-500',
    'F': 'bg-gray-500',
  };
  return colors[reliability] || colors['C'];
}

export function getTagColor(tag: string): string {
  const colors: Record<string, string> = {
    'Факт': 'bg-green-100 text-green-800',
    'Аналитика': 'bg-blue-100 text-blue-800',
    'Предположение': 'bg-amber-100 text-amber-800',
    'Предупреждение': 'bg-red-100 text-red-800',
  };
  return colors[tag] || colors['Аналитика'];
}

export function getTrendIcon(trend: string): string {
  const icons: Record<string, string> = {
    'up': '↑',
    'down': '↓',
    'stable': '→',
  };
  return icons[trend] || '→';
}

export function getTrendColor(trend: string, isPositive: boolean = true): string {
  if (trend === 'stable') return 'text-slate-600';
  if (trend === 'up') return isPositive ? 'text-green-600' : 'text-red-600';
  return isPositive ? 'text-red-600' : 'text-green-600';
}