import { Task } from '@/types';

export const tasks: Task[] = [
  {
    id: 'task-1',
    name: 'Подготовка и подача материалов в MIC',
    description: 'Подготовка полного пакета документов для подачи заявки в Myanmar Investment Commission',
    category: 'Процедура MIC',
    projectId: 'proj-1',
    assigneeId: 'user-2',
    observers: ['user-1'],
    status: 'Завершено',
    priority: 'Высокий',
    startDate: '2024-01-15',
    endDate: '2024-02-15',
    duration: 30,
    budget: 50000,
    dependencies: [],
    progress: 100,
    subtasks: [
      { id: 'st-1-1', name: 'Сбор учредительных документов', completed: true },
      { id: 'st-1-2', name: 'Подготовка бизнес-плана', completed: true },
      { id: 'st-1-3', name: 'Финансовая модель', completed: true },
      { id: 'st-1-4', name: 'Подача заявки', completed: true },
    ],
  },
  {
    id: 'task-2',
    name: 'Получение разрешений на импорт оборудования',
    description: 'Оформление импортных разрешений для производственного оборудования',
    category: 'Ключевые документы проекта',
    projectId: 'proj-1',
    assigneeId: 'user-3',
    observers: ['user-1', 'user-2'],
    status: 'Завершено',
    priority: 'Высокий',
    startDate: '2024-02-20',
    endDate: '2024-04-10',
    duration: 50,
    dependencies: ['task-1'],
    progress: 100,
    subtasks: [
      { id: 'st-2-1', name: 'Список оборудования', completed: true },
      { id: 'st-2-2', name: 'Подача в таможню', completed: true },
      { id: 'st-2-3', name: 'Получение разрешения', completed: true },
    ],
  },
  {
    id: 'task-3',
    name: 'Получение налоговых стимулов',
    description: 'Регистрация в Free Zone для получения 7 лет налоговых каникул',
    category: 'Процедура MIC',
    projectId: 'proj-1',
    assigneeId: 'user-2',
    observers: ['user-1'],
    status: 'Завершено',
    priority: 'Средний',
    startDate: '2024-02-01',
    endDate: '2024-03-15',
    duration: 43,
    dependencies: ['task-1'],
    progress: 100,
    subtasks: [
      { id: 'st-3-1', name: 'Подготовка документов', completed: true },
      { id: 'st-3-2', name: 'Согласование с Ministry of Planning', completed: true },
      { id: 'st-3-3', name: 'Получение подтверждения', completed: true },
    ],
  },
  {
    id: 'task-4',
    name: 'Завершение процедуры MIC',
    description: 'Получение окончательного одобрения от MIC',
    category: 'Процедура MIC',
    projectId: 'proj-1',
    assigneeId: 'user-2',
    observers: ['user-1'],
    status: 'Частично выполнено',
    priority: 'Критический',
    startDate: '2024-02-15',
    endDate: '2024-03-01',
    duration: 15,
    dependencies: ['task-1'],
    progress: 85,
    subtasks: [
      { id: 'st-4-1', name: 'Рассмотрение заявки', completed: true },
      { id: 'st-4-2', name: 'Запрос дополнительных документов', completed: true },
      { id: 'st-4-3', name: 'Финальное одобрение', completed: false },
    ],
  },
  {
    id: 'task-5',
    name: 'Сертификация сырья и компонентов',
    description: 'Получение сертификатов соответствия для используемых материалов',
    category: 'Сертификация продукции',
    projectId: 'proj-1',
    assigneeId: 'user-5',
    observers: ['user-2'],
    status: 'По графику',
    priority: 'Высокий',
    startDate: '2024-09-01',
    endDate: '2024-11-30',
    duration: 90,
    dependencies: ['task-8'],
    progress: 60,
    subtasks: [
      { id: 'st-5-1', name: 'Тестирование образцов', completed: true },
      { id: 'st-5-2', name: 'Подача в сертификационный орган', completed: true },
      { id: 'st-5-3', name: 'Получение GOST сертификата', completed: false },
      { id: 'st-5-4', name: 'Получение Myanmar сертификата', completed: false },
    ],
  },
  {
    id: 'task-6',
    name: 'Подписание договора на строительство',
    description: 'Заключение контракта с подрядчиком на строительные работы',
    category: 'Проект строительства',
    projectId: 'proj-1',
    assigneeId: 'user-3',
    observers: ['user-1', 'user-2'],
    status: 'Завершено',
    priority: 'Высокий',
    startDate: '2024-03-01',
    endDate: '2024-03-15',
    duration: 14,
    dependencies: ['task-4'],
    progress: 100,
    subtasks: [
      { id: 'st-6-1', name: 'Выбор подрядчика', completed: true },
      { id: 'st-6-2', name: 'Согласование условий', completed: true },
      { id: 'st-6-3', name: 'Подписание контракта', completed: true },
    ],
  },
  {
    id: 'task-7',
    name: 'Закупка инженерного оборудования (Китай)',
    description: 'Закупка и доставка производственного оборудования из Китая',
    category: 'Доставка сырья',
    projectId: 'proj-1',
    assigneeId: 'user-3',
    observers: ['user-2'],
    status: 'Завершено',
    priority: 'Высокий',
    startDate: '2024-04-01',
    endDate: '2024-06-30',
    duration: 90,
    budget: 1200000,
    dependencies: ['task-2'],
    progress: 100,
    subtasks: [
      { id: 'st-7-1', name: 'Выбор поставщика', completed: true },
      { id: 'st-7-2', name: 'Заказ оборудования', completed: true },
      { id: 'st-7-3', name: 'Доставка в Мьянму', completed: true },
      { id: 'st-7-4', name: 'Таможенная очистка', completed: true },
    ],
  },
  {
    id: 'task-8',
    name: 'Монтаж производственной линии',
    description: 'Установка и наладка производственного оборудования',
    category: 'Монтаж оборудования',
    projectId: 'proj-1',
    assigneeId: 'user-5',
    observers: ['user-2'],
    status: 'Завершено',
    priority: 'Критический',
    startDate: '2024-07-01',
    endDate: '2024-09-15',
    duration: 76,
    budget: 300000,
    dependencies: ['task-7'],
    progress: 100,
    subtasks: [
      { id: 'st-8-1', name: 'Распаковка оборудования', completed: true },
      { id: 'st-8-2', name: 'Монтаж', completed: true },
      { id: 'st-8-3', name: 'Пусконаладка', completed: true },
      { id: 'st-8-4', name: 'Тестирование', completed: true },
    ],
  },
  {
    id: 'task-9',
    name: 'Запуск продаж',
    description: 'Подготовка и запуск системы продаж продукции',
    category: 'Система продаж',
    projectId: 'proj-1',
    assigneeId: 'user-2',
    observers: ['user-1'],
    status: 'Не начато',
    priority: 'Высокий',
    startDate: '2024-11-15',
    endDate: '2024-12-30',
    duration: 45,
    dependencies: ['task-5'],
    progress: 0,
    subtasks: [
      { id: 'st-9-1', name: 'Разработка ценовой политики', completed: false },
      { id: 'st-9-2', name: 'Поиск дистрибьюторов', completed: false },
      { id: 'st-9-3', name: 'Заключение договоров', completed: false },
      { id: 'st-9-4', name: 'Первые поставки', completed: false },
    ],
  },
  {
    id: 'task-10',
    name: 'Расширение продуктовой линейки',
    description: 'Разработка и вывод на рынок новых продуктов',
    category: 'Разработка продуктов',
    projectId: 'proj-1',
    assigneeId: 'user-5',
    observers: ['user-2'],
    status: 'Будущая задача',
    priority: 'Средний',
    startDate: '2025-01-01',
    endDate: '2025-06-30',
    duration: 180,
    dependencies: ['task-9'],
    progress: 0,
    subtasks: [],
  },
  {
    id: 'task-11',
    name: 'Геологическая разведка месторождения',
    description: 'Детальная геологическая разведка никелевого месторождения',
    category: 'Площадка',
    projectId: 'proj-2',
    assigneeId: 'user-4',
    observers: ['user-1'],
    status: 'Завершено',
    priority: 'Критический',
    startDate: '2023-06-01',
    endDate: '2023-09-30',
    duration: 121,
    budget: 800000,
    dependencies: [],
    progress: 100,
    subtasks: [
      { id: 'st-11-1', name: 'Бурение скважин', completed: true },
      { id: 'st-11-2', name: 'Анализ образцов', completed: true },
      { id: 'st-11-3', name: 'Подготовка отчета', completed: true },
    ],
  },
  {
    id: 'task-12',
    name: 'Получение лицензии на добычу',
    description: 'Оформление лицензии на промышленную добычу никеля',
    category: 'Процедура MIC',
    projectId: 'proj-2',
    assigneeId: 'user-4',
    observers: ['user-1'],
    status: 'Завершено',
    priority: 'Критический',
    startDate: '2023-10-01',
    endDate: '2024-01-15',
    duration: 106,
    dependencies: ['task-11'],
    progress: 100,
    subtasks: [
      { id: 'st-12-1', name: 'Подготовка документов', completed: true },
      { id: 'st-12-2', name: 'Экологическая экспертиза', completed: true },
      { id: 'st-12-3', name: 'Получение лицензии', completed: true },
    ],
  },
  {
    id: 'task-13',
    name: 'Строительство подъездных дорог',
    description: 'Строительство инфраструктуры доступа к месторождению',
    category: 'Ремонт и строительство',
    projectId: 'proj-2',
    assigneeId: 'user-4',
    observers: [],
    status: 'Завершено',
    priority: 'Высокий',
    startDate: '2024-02-01',
    endDate: '2024-08-01',
    duration: 182,
    budget: 2000000,
    dependencies: ['task-12'],
    progress: 100,
    subtasks: [
      { id: 'st-13-1', name: 'Проектирование дорог', completed: true },
      { id: 'st-13-2', name: 'Строительство', completed: true },
    ],
  },
  {
    id: 'task-14',
    name: 'Закупка горного оборудования',
    description: 'Закупка экскаваторов, самосвалов и другой техники',
    category: 'Доставка сырья',
    projectId: 'proj-2',
    assigneeId: 'user-6',
    observers: ['user-4'],
    status: 'По графику',
    priority: 'Высокий',
    startDate: '2024-06-01',
    endDate: '2024-12-31',
    duration: 213,
    budget: 5000000,
    dependencies: ['task-12'],
    progress: 70,
    subtasks: [
      { id: 'st-14-1', name: 'Тендер на поставку', completed: true },
      { id: 'st-14-2', name: 'Заказ оборудования', completed: true },
      { id: 'st-14-3', name: 'Доставка первой партии', completed: true },
      { id: 'st-14-4', name: 'Доставка второй партии', completed: false },
    ],
  },
  {
    id: 'task-15',
    name: 'Начало промышленной добычи',
    description: 'Запуск промышленной добычи никелевой руды',
    category: 'Эксплуатация',
    projectId: 'proj-2',
    assigneeId: 'user-4',
    observers: ['user-1', 'user-6'],
    status: 'Будущая задача',
    priority: 'Критический',
    startDate: '2025-03-01',
    endDate: '2025-05-01',
    duration: 61,
    dependencies: ['task-13', 'task-14'],
    progress: 0,
    subtasks: [],
  },
  {
    id: 'task-16',
    name: 'Модернизация шахтных выработок',
    description: 'Расширение и модернизация существующих шахтных выработок',
    category: 'Ремонт и строительство',
    projectId: 'proj-3',
    assigneeId: 'user-4',
    observers: ['user-1'],
    status: 'По графику',
    priority: 'Высокий',
    startDate: '2024-06-01',
    endDate: '2025-01-15',
    duration: 228,
    budget: 8000000,
    dependencies: [],
    progress: 55,
    subtasks: [
      { id: 'st-16-1', name: 'Оценка текущего состояния', completed: true },
      { id: 'st-16-2', name: 'Проектирование расширения', completed: true },
      { id: 'st-16-3', name: 'Проходка новых тоннелей', completed: false },
    ],
  },
  {
    id: 'task-17',
    name: 'Установка новой обогатительной линии',
    description: 'Монтаж современной линии обогащения руды',
    category: 'Монтаж оборудования',
    projectId: 'proj-3',
    assigneeId: 'user-7',
    observers: ['user-4'],
    status: 'Частично выполнено',
    priority: 'Критический',
    startDate: '2024-09-01',
    endDate: '2025-04-01',
    duration: 212,
    budget: 12000000,
    dependencies: [],
    progress: 45,
    subtasks: [
      { id: 'st-17-1', name: 'Закупка оборудования', completed: true },
      { id: 'st-17-2', name: 'Подготовка площадки', completed: true },
      { id: 'st-17-3', name: 'Монтаж', completed: false },
      { id: 'st-17-4', name: 'Пусконаладка', completed: false },
    ],
  },
  {
    id: 'task-18',
    name: 'Получение экспортных сертификатов',
    description: 'Сертификация продукции для экспорта',
    category: 'Сертификация продукции',
    projectId: 'proj-3',
    assigneeId: 'user-7',
    observers: ['user-1'],
    status: 'Отложено',
    priority: 'Средний',
    startDate: '2025-02-01',
    endDate: '2025-05-01',
    duration: 89,
    dependencies: ['task-17'],
    progress: 0,
    subtasks: [],
  },
  {
    id: 'task-19',
    name: 'Разработка системы экологического мониторинга',
    description: 'Создание системы контроля воздействия на окружающую среду',
    category: 'Технологический проект',
    projectId: 'proj-3',
    assigneeId: 'user-7',
    observers: ['user-4'],
    status: 'По графику',
    priority: 'Средний',
    startDate: '2024-08-01',
    endDate: '2024-12-31',
    duration: 152,
    dependencies: [],
    progress: 65,
    subtasks: [
      { id: 'st-19-1', name: 'Установка датчиков', completed: true },
      { id: 'st-19-2', name: 'Настройка ПО', completed: true },
      { id: 'st-19-3', name: 'Тестирование системы', completed: false },
    ],
  },
  {
    id: 'task-20',
    name: 'Полевые испытания биопрепаратов',
    description: 'Проведение полевых испытаний новых биопрепаратов',
    category: 'Разработка продуктов',
    projectId: 'proj-7',
    assigneeId: 'user-9',
    observers: ['user-5'],
    status: 'По графику',
    priority: 'Высокий',
    startDate: '2024-07-01',
    endDate: '2025-01-31',
    duration: 214,
    dependencies: [],
    progress: 50,
    subtasks: [
      { id: 'st-20-1', name: 'Выбор тестовых площадок', completed: true },
      { id: 'st-20-2', name: 'Посев первой культуры', completed: true },
      { id: 'st-20-3', name: 'Мониторинг роста', completed: false },
      { id: 'st-20-4', name: 'Анализ результатов', completed: false },
    ],
  },
  {
    id: 'task-21',
    name: 'Дать пизды МЭКу',
    description: 'Контроль процесса выдачи лицензий от Myanmar Investment Commission',
    category: 'Процедура MIC',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    observers: [],
    status: 'Частично выполнено',
    priority: 'Критический',
    startDate: '2024-12-01',
    endDate: '2025-01-15',
    duration: 45,
    dependencies: [],
    progress: 40,
    subtasks: [
      { id: 'st-21-1', name: 'Связаться с представителем МЭК', completed: true },
      { id: 'st-21-2', name: 'Проверить статус заявки', completed: false },
      { id: 'st-21-3', name: 'Получить лицензию', completed: false },
    ],
  },
  {
    id: 'task-22',
    name: 'Перетереть с Алимовым по крипте',
    description: 'Оказать давление на Myanmar Investment Commission для ускорения процессов',
    category: 'Процедура MIC',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    observers: [],
    status: 'Частично выполнено',
    priority: 'Высокий',
    startDate: '2024-12-10',
    endDate: '2025-01-31',
    duration: 52,
    dependencies: ['task-21'],
    progress: 25,
    subtasks: [
      { id: 'st-22-1', name: 'Подготовить аргументы', completed: true },
      { id: 'st-22-2', name: 'Встреча с руководством МЭК', completed: false },
      { id: 'st-22-3', name: 'Добиться ускорения', completed: false },
    ],
  },
  {
    id: 'task-23',
    name: 'Нарулить тему с горючкой',
    description: 'Разрешение проблем с поставкой и лицензированием нефтепродуктов',
    category: 'Доставка сырья',
    projectId: 'proj-1',
    assigneeId: 'user-1',
    observers: [],
    status: 'Частично выполнено',
    priority: 'Высокий',
    startDate: '2024-12-05',
    endDate: '2025-02-28',
    duration: 85,
    dependencies: [],
    progress: 30,
    subtasks: [
      { id: 'st-23-1', name: 'Анализ текущей ситуации', completed: true },
      { id: 'st-23-2', name: 'Переговоры с поставщиками', completed: false },
      { id: 'st-23-3', name: 'Получение разрешений', completed: false },
      { id: 'st-23-4', name: 'Организация поставок', completed: false },
    ],
  },
];
