import { User, Stakeholder, Role, AuditLog, Risk } from '@/types';

export const users: User[] = [
  {
    id: 'user-1',
    name: 'Шатиров Сергей',
    email: 'a.petrov@rc-investment.com',
    roleId: 'role-1',
    department: 'Руководство',
  },
  {
    id: 'user-2',
    name: 'Воеводин Александр',
    email: 'm.ivanova@ruma-organic.mm',
    roleId: 'role-2',
    department: 'Проектное управление',
  },
  {
    id: 'user-3',
    name: 'Гуляева Ольга',
    email: 'd.sidorov@rc-investment.com',
    roleId: 'role-3',
    department: 'Юридический отдел',
  },
  {
    id: 'user-4',
    name: 'Алимов Артемий',
    email: 's.kozlov@rcm.mm',
    roleId: 'role-2',
    department: 'Региональный руководитель',
  },
  {
    id: 'user-5',
    name: 'Белошицкая Александра',
    email: 'e.smirnova@ruma-organic.mm',
    roleId: 'role-4',
    department: 'Исполнительный директор',
  },
  {
    id: 'user-6',
    name: 'Коваленко Олег',
    email: 'a.novikov@rcm.mm',
    roleId: 'role-4',
    department: 'Снабжение',
  },
  {
    id: 'user-7',
    name: 'Морозов Игорь',
    email: 'i.morozov@myanmar-metals.gov.mm',
    roleId: 'role-4',
    department: 'Инженерный отдел',
  },
  {
    id: 'user-8',
    name: 'Волкова Ольга',
    email: 'o.volkova@rc-investment.com',
    roleId: 'role-3',
    department: 'Логистика',
  },
  {
    id: 'user-9',
    name: 'Лебедев Павел',
    email: 'p.lebedev@ruma-organic.mm',
    roleId: 'role-4',
    department: 'Исследования',
  },
];

export const stakeholders: Stakeholder[] = [
  {
    id: 'stake-1',
    name: 'Aung Ko Ko',
    position: 'Director',
    companyId: 'comp-2',
    type: 'Оператор',
    contact: {
      phone: '+95 1 234 5678',
      email: 'aung.koko@ruma-organic.mm',
    },
    projects: ['proj-1', 'proj-6', 'proj-7'],
  },
  {
    id: 'stake-2',
    name: 'U Tin Maung',
    position: 'CEO',
    companyId: 'comp-3',
    type: 'Партнер',
    contact: {
      phone: '+95 1 345 6789',
      email: 'u.tinmaung@athagri.mm',
    },
    projects: ['proj-6', 'proj-7'],
  },
  {
    id: 'stake-3',
    name: 'Wang Wei',
    position: 'Project Manager',
    companyId: 'comp-6',
    type: 'Партнер',
    contact: {
      phone: '+86 10 1234 5678',
      email: 'wang.wei@cnmc.com.cn',
    },
    projects: ['proj-2'],
  },
  {
    id: 'stake-4',
    name: 'Dr. Kyaw Soe',
    position: 'Director General',
    companyId: 'comp-8',
    type: 'Министерство/Ведомство',
    contact: {
      phone: '+95 67 123 456',
      email: 'kyaw.soe@mic.gov.mm',
    },
    projects: [],
  },
  {
    id: 'stake-5',
    name: 'Daw Mya Thin',
    position: 'Deputy Director',
    companyId: 'comp-10',
    type: 'Министерство/Ведомство',
    contact: {
      phone: '+95 67 345 678',
      email: 'mya.thin@agriculture.gov.mm',
    },
    projects: ['proj-6', 'proj-7'],
  },
];

export const roles: Role[] = [
  {
    id: 'role-1',
    name: 'Администратор безопасности',
    description: 'Полный доступ ко всем разделам системы',
    permissions: {
      projects: 'admin',
      tasks: 'admin',
      documents: 'admin',
      companies: 'admin',
      analytics: 'admin',
      security: 'admin',
    },
  },
  {
    id: 'role-2',
    name: 'Руководитель проекта',
    description: 'Управление проектами и задачами',
    permissions: {
      projects: 'write',
      tasks: 'write',
      documents: 'write',
      companies: 'read',
      analytics: 'read',
      security: 'none',
    },
  },
  {
    id: 'role-3',
    name: 'Проектный офис',
    description: 'Доступ к проектам, задачам и документам',
    permissions: {
      projects: 'read',
      tasks: 'write',
      documents: 'write',
      companies: 'read',
      analytics: 'read',
      security: 'none',
    },
  },
  {
    id: 'role-4',
    name: 'Исполнитель',
    description: 'Выполнение задач и просмотр документов',
    permissions: {
      projects: 'read',
      tasks: 'write',
      documents: 'read',
      companies: 'read',
      analytics: 'none',
      security: 'none',
    },
  },
  {
    id: 'role-5',
    name: 'Внешний контрагент',
    description: 'Ограниченный доступ к связанным проектам',
    permissions: {
      projects: 'read',
      tasks: 'read',
      documents: 'read',
      companies: 'read',
      analytics: 'none',
      security: 'none',
    },
  },
  {
    id: 'role-6',
    name: 'Наблюдатель',
    description: 'Только чтение',
    permissions: {
      projects: 'read',
      tasks: 'read',
      documents: 'read',
      companies: 'read',
      analytics: 'read',
      security: 'none',
    },
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    userId: 'user-2',
    userName: 'Иванова Мария',
    action: 'view',
    objectType: 'document',
    objectId: 'doc-2',
    objectName: 'MIC Approval Letter',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'audit-2',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    userId: 'user-3',
    userName: 'Сидоров Дмитрий',
    action: 'upload',
    objectType: 'document',
    objectId: 'doc-1',
    objectName: 'Договор на строительство Mobile Factory',
    ipAddress: '192.168.1.67',
  },
  {
    id: 'audit-3',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    userId: 'user-1',
    userName: 'Петров Алексей',
    action: 'edit',
    objectType: 'project',
    objectId: 'proj-1',
    objectName: 'Mobile Factory Ruma',
    ipAddress: '192.168.1.23',
    details: 'Обновлен прогресс проекта до 78%',
  },
  {
    id: 'audit-4',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user-4',
    userName: 'Козлов Сергей',
    action: 'view',
    objectType: 'document',
    objectId: 'doc-9',
    objectName: 'Геологический отчет Tagaung Taung',
    ipAddress: '192.168.1.89',
  },
  {
    id: 'audit-5',
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    userId: 'user-5',
    userName: 'Смирнова Елена',
    action: 'edit',
    objectType: 'task',
    objectId: 'task-5',
    objectName: 'Сертификация сырья и компонентов',
    ipAddress: '192.168.1.112',
    details: 'Обновлен статус задачи',
  },
];

export const risks: Risk[] = [
  {
    id: 'risk-1',
    title: 'Задержка сертификации продукции',
    description: 'Процесс получения сертификатов GOST и Myanmar занимает больше времени, чем планировалось',
    level: 'Высокий',
    probability: 80,
    impact: 75,
    projectId: 'proj-1',
    status: 'В обработке',
    mitigationPlan: 'Параллельная подача документов в оба органа, привлечение консультантов',
    owner: 'user-5',
    detectedDate: '2026-10-15',
  },
  {
    id: 'risk-2',
    title: 'Задержка поставки горного оборудования',
    description: 'Возможная задержка доставки экскаваторов и самосвалов из Китая',
    level: 'Средний',
    probability: 50,
    impact: 60,
    projectId: 'proj-2',
    status: 'Выявлен',
    mitigationPlan: 'Поиск альтернативных поставщиков, корректировка графика',
    owner: 'user-6',
    detectedDate: '2026-11-01',
  },
  {
    id: 'risk-3',
    title: 'Необходимость усиления мер безопасности',
    description: 'После инспекции выявлена необходимость дополнительных мер безопасности в шахте',
    level: 'Высокий',
    probability: 90,
    impact: 80,
    projectId: 'proj-3',
    status: 'В обработке',
    mitigationPlan: 'Закупка дополнительного оборудования, обучение персонала',
    owner: 'user-4',
    detectedDate: '2026-09-20',
  },
  {
    id: 'risk-4',
    title: 'Изменение налогового законодательства',
    description: 'Возможные изменения в налоговых стимулах для Free Zone',
    level: 'Средний',
    probability: 30,
    impact: 70,
    projectId: 'proj-1',
    status: 'Выявлен',
    mitigationPlan: 'Мониторинг законодательства, консультации с юристами',
    owner: 'user-3',
    detectedDate: '2026-10-01',
  },
  {
    id: 'risk-5',
    title: 'Отсутствие квалифицированного персонала',
    description: 'Сложности с наймом квалифицированных специалистов для нового проекта',
    level: 'Высокий',
    probability: 70,
    impact: 65,
    projectId: 'proj-10',
    status: 'Выявлен',
    mitigationPlan: 'Программа обучения, привлечение экспертов из других проектов',
    owner: 'user-2',
    detectedDate: '2026-10-25',
  },
];
